### ISSUE TITLE
YAML locations with altitude

### ISSUE THREAD

**Issue by Moonbase59** [valentine195/obsidian-leaflet-plugin#105]
Since I plan to extend my use of the YAML fontmatter `location: [lat, lng]` to include the _altitude_, I was wondering if this is already supported, since Leaflet’s `LatLng` _does_ support a third altitude parameter (in meters).

I’ve tried it, using `location: [48.2443648, 10.3631767, 512]`, and it breaks neither my existing code nor _Obsidian Leaflet_. We might never use it in the plugin, but it shouldn’t break.

Can you confirm?

**Comment by valentine195** [comment]
Sorry, missed this. 

Should not be an issue.

**Comment by Moonbase59** [comment]
Perfect, so I can go ahead. The Route 66 GeoJSON file mentioned in the discussions also has 3-number location data, and works. Great!
