### ISSUE TITLE
Use local image file

### ISSUE THREAD

**Issue by trungng2006** [valentine195/obsidian-leaflet-plugin#11]
It would be very nice if the user can utilize local picture for this plugin. Would it be possible to implement this feature?

**Comment by valentine195** [comment]
Hi, yes, you can (added in #6 / release 0.1.9). I'm currently updating the readme file to show how you can do this, but you can use an obsidian url or a direct path to an image:

Image maps can be loaded one of three ways:

1. Direct URL (e.g., https://i.imgur.com/jH8j3mJ.jpg)
2. Obsidian URL (e.g., obsidian://open?vault=VaultName&file=Path/To/Image.jpg)
3. Direct path to image (e.g., Path/To/Image.jpg)

**Comment by trungng2006** [comment]
Thank you so much!!!
