### ISSUE TITLE
Auto-zoom to GeoJSON

### ISSUE THREAD

**Issue by valentine195** [valentine195/obsidian-leaflet-plugin#111]
If you have many notes showing interesting GeoJSON-coded areas, like @oyvindsolstad’s Interstates, or in my case, countries with states and districts, it’s quite some work to figure the correct map center and zoom.

Usability stuff again, hee hee. I was wondering if it could be possible to

- collect _all_ GeoJSON FeatureCollections (Features) given in a map’s code block,
- determine the common _center_ and _bounding box_, then
- autocenter and autozoom the map based on that
- _if_ a special variable in the code block was set to truthy, like `zoomFeatures: true`?

This would allow to much more easily create notes with maps showing GeoJSON-coded areas, much like some online services do.

I found an [interesting idea on StackOverflow](https://stackoverflow.com/a/65931657), maybe some of this us usable?

What do you think about this idea?

_Originally posted by @Moonbase59 in https://github.com/valentine195/obsidian-leaflet-plugin/discussions/110_

**Comment by valentine195** [comment]
Added in 3.18.3

**Comment by Moonbase59** [comment]
Works so far, thanks! Have to try with multiple GeoJSON, still.

_But_ (as always)

- "Reset View" and
- "Show all markers"

behave oddly.

I’d expect at least "Reset View" would take one back to the _calculated_ view _if_ `zoomFeatures: true`, don’t you think?

**Comment by Moonbase59** [comment]
Further testing:

- multiple GeoJSON files: okay

And: **Wow, that _is_ a nice feature!**

**Comment by valentine195** [comment]
> "Show all markers"

Can you let me know how this is behaving oddly? It is showing all markers, for me.

> I’d expect at least "Reset View" would take one back to the calculated view if zoomFeatures: true, don’t you think?

Will be in the next release.

**Comment by Moonbase59** [comment]
Great. I had _no_ markers set for this simple test:

````
```leaflet
id: route66
#lat: 37.6556
#long: -101.7334
minZoom: 4
maxZoom: 18
#defaultZoom: 4.5
zoomDelta: 0.5
zoomFeatures: true
geojson: 
  - [[geo-usa-route66.geojson]]
  #- [[geo-bayern-landkreise.geojson]]
```
````

**Comment by valentine195** [comment]
"Show All Markers" displays the entire map world if there are no markers defined.

**Comment by Moonbase59** [comment]
![Auswahl_148](https://user-images.githubusercontent.com/3706922/122421616-ca387200-cf8c-11eb-89a0-45181f1fa85c.png)

Above test map, clicked on "Show all markers"

**Comment by valentine195** [comment]
It's because of your `minZoom`. The map is showing [0, 0] at the furthest zoom it can.

**Comment by Moonbase59** [comment]
You’re correct, I forgot the `minZoom`!

**Comment by valentine195** [comment]
Honestly, now that I'm thinking about it, it probably doesn't make sense to even display that button if there are no markers on the map.

**Comment by Moonbase59** [comment]
Now that you say it … you’re right. Maybe gray it out?

**Comment by Moonbase59** [comment]
N.B.: It should probably be mentioned in the docs that `zoomDelta` plays a big role in _how big the zoom will be_ if `zoomFeatures` is used.

**Comment by Moonbase59** [comment]
A-hem, I _still_ have a new idea: If you have multiple features, and you click on one, the tooltip is now moved to "here"—very usable.

What would you think if one Ctrl+clicked on a shown feature, and it would auto-zoom into "this" feature? (I.e., a district in a multi-district GeoJSON)

**Comment by Moonbase59** [comment]
Here is a map and some test data to show what I mean:

````
```leaflet
id: route66
#lat: 37.6556
#long: -101.7334
#minZoom: 4
maxZoom: 18
#defaultZoom: 4.5
zoomDelta: 0.5
zoomFeatures: true
geojson: 
  #- [[geo-usa-route66.geojson]]
  - [[geo-bayern-landkreise.geojson]]
  - [[geo-lk-günzburg-gemeinden.geojson]]
```
````
[geojson-testdata.zip](https://github.com/valentine195/obsidian-leaflet-plugin/files/6671316/geojson-testdata.zip)

**Comment by Moonbase59** [comment]
Fault: If you have a "nearby" map with districts and _just_ move the mouse around into a neighbouring district (no dragging or clicking), the map will suddenly _move_, apparently to show the (centered) tooltip of the neighbouring district. Urgs. No good. I think it shouldn’t do it.

**Comment by valentine195** [comment]
Hmm... I have auto panning off for the popup. It shouldn't be moving the map.

**Comment by Moonbase59** [comment]
Not even with map & data from above? Odd … It worked (i.e. didn’t auto-pan) in 3.18.2.

**Comment by valentine195** [comment]
> What would you think if one Ctrl+clicked on a shown feature, and it would auto-zoom into "this" feature? (I.e., a district in a multi-district GeoJSON, or part of a route)

Added in 3.18.4

**Comment by Moonbase59** [comment]
Restarted everything, just to be sure, still jumps around wildly:

![Peek 2021-06-17 17-39](https://user-images.githubusercontent.com/3706922/122429462-17b7dd80-cf93-11eb-9b78-111a6741e56f.gif)

**Comment by valentine195** [comment]
No, I can't get mine to jump around. The popups are displayed off-screen (which is expected with `autoPan: false`).

> It worked (i.e. didn’t auto-pan) in 3.18.2.

Interesting. I think 3.18.4 will fix this, albeit unintentionally.

**Comment by Moonbase59** [comment]
3.18.4:

- Ok, stopped "jumping" in 3.18.4.
- "Reset view" jumps not to the calculated, but a much larger area:
  ![Auswahl_150](https://user-images.githubusercontent.com/3706922/122430491-f2779f00-cf93-11eb-93e5-75e2d2246a3c.png)
- Ctrl+click on a GeoJSON feature works fine, albeit not on parts of a route (lines). Use the Route 66 file from the discussion.
- "Current overlay" overlays everything until unfiltered, no access to overlays beneath.

**Comment by valentine195** [comment]
> "Reset view" jumps not to the calculated, but a much larger area:

I update the zoom to the map's displayed zoom level when this feature is active. Weird. I'll investigate.

> Ctrl+click on a GeoJSON feature works fine, albeit not on parts of a route (lines). Use the Route 66 file from the discussion.

The Ctrl-click zoom will only be able to zoom on distinct `feature` entries of a GeoJSON file.

> "Current overlay" overlays everything until unfiltered, no access to overlays beneath.

Hmm, nothing changed for this code. I'll investigate this too.

**Comment by Moonbase59** [comment]
> The Ctrl-click zoom will only be able to zoom on distinct `feature` entries of a GeoJSON file.

Absolutely clear. My "route66" file _has_ lots of separated features.

**Comment by valentine195** [comment]
That file works for me to Ctrl-click zoom to distinct parts, but it is a little difficult to actually position the mouse correctly on the line.

**Comment by Moonbase59** [comment]
True, I might have to add stroke-width. For some reason, after changing around in the code block (changing geojson files), it now also works here using 3.18.4. Could it be that after upgrading from 3.18.3 to 3.18.4, it somehow kept something cached, even after closing/reopening Obsidian?

**Comment by valentine195** [comment]
I wouldn't expect that... hard to say what Obsidian is doing, though.

**Comment by valentine195** [comment]
> "Current overlay" overlays everything until unfiltered, no access to overlays beneath.

Is this still happening and, if so, can you explain what you mean by "Current overlay"? Using this, they are sorting correctly:


---
#location: [48.323380433488, 10.443368000767947] # Start Nord
location: [48.2969, 10.459] # Start Süd
mapmarker: location
# The map overlay shows 11 stations of an educational nature trail
mapoverlay:
  - ['rgba(192, 0, 192, .6)', [48.2969, 10.459], 5 m, "GIEP Startpunkt Süd"]
  - ['rgba(192, 0, 192, .6)', [48.301, 10.4565], 5 m, "GIEP 1. Kanal und Wehr, Fischtreppe"]
  - ['rgba(192, 0, 192, .6)', [48.3061, 10.4542], 5 m, "GIEP 2. Fischregionen, Heimische Fische"]
  - ['rgba(192, 0, 192, .6)', [48.3072, 10.4487], 5 m, "GIEP 3. Ausgleichsfläche, Amphibien, Vegetation Kühgraben"]
  - ['rgba(192, 0, 192, .6)', [48.3118, 10.4463], 5 m, "GIEP 4. Element Wasser, Spielplatz"]
  - ['rgba(192, 0, 192, .6)', [48.3131, 10.4495], 5 m, "GIEP 5. Wasservögel, Hochwasser"]
  - ['rgba(192, 0, 192, .6)', [48.314, 10.449], 5 m, "GIEP 6. Uferbegleitvegetation"]
  - ['rgba(192, 0, 192, .6)', [48.3163, 10.4474], 5 m, "GIEP 7. Wasserkraft, Mühlengeschichte"]
  - ['rgba(192, 0, 192, .6)', [48.3193, 10.4481], 5 m, "GIEP 8. Weißstorch"]
  - ['rgba(192, 0, 192, .6)', [48.3188, 10.4458], 5 m, "GIEP 9. Kiesabbau"]
  - ['rgba(192, 0, 192, .6)', [48.3192, 10.4455], 5 m, "GIEP 10. Biber"]
  - ['rgba(192, 0, 192, .6)', [48.3216, 10.4441], 5 m, "GIEP 11. Naturraum Mindeltal"]
  - ['rgba(192, 0, 192, .6)', [48.3234, 10.4437], 5 m, "GIEP Startpunkt Nord"]

nearby: 2 km
---

**Comment by Moonbase59** [comment]
Added https://github.com/valentine195/obsidian-leaflet-plugin/files/6671787/geo-usa-route66-edit2.geojson.zip using a `stroke-width` of `3`, for better clicking. :-)

Sorry, the overlay gotten from the "-Current Location" note, which produces an overlay that is _very_ near by the "Matthias C. Hormann" one. This doesn’t let me get at anything below it. When unfiltering "Current", I see the other overlay’s tooltips, even the "GIEP" stations when having a steady hand …

**Comment by Moonbase59** [comment]
![Auswahl_151](https://user-images.githubusercontent.com/3706922/122438523-15598180-cf9b-11eb-86ce-7bbc0e4ee671.png)

**Comment by Moonbase59** [comment]
When unfiltering it, I can even get at the "GIEP" thingies:

![Auswahl_152](https://user-images.githubusercontent.com/3706922/122438763-58b3f000-cf9b-11eb-8ff7-ce674a8877e9.png)

![Auswahl_153](https://user-images.githubusercontent.com/3706922/122438779-5d78a400-cf9b-11eb-9992-8233c479c749.png)

**Comment by valentine195** [comment]
Ah, I know what's going on.

This is actually what was causing the issue initially. In order to support filtering out the overlays with their associated marker types, I am adding them to something called a "feature group" in Leaflet, which then allows me to just remove the entire feature group when filtered out.

Unfortunately, Leaflet draws these feature groups in order - so the overlays associated to one marker get drawn, then the overlays associated with another, regardless of my sort order.

I'll need to do some refactoring to support filtering without adding them to different layer groups.

**Comment by Moonbase59** [comment]
Starts getting complicated, with all these layers and groups, sorry for that! But somehow I can feel you also intend to make this the greatest-ever map plugin, and thanks for that!

It actually already _is_, in so many aspects.

**Comment by valentine195** [comment]
>"Reset view" jumps not to the calculated, but a much larger area:

> "Current overlay" overlays everything until unfiltered, no access to overlays beneath.

Should be fixed in 3.18.5

**Comment by Moonbase59** [comment]
Man, you got _crazy_ turnaround times on these things! :hugs: … Testing …

**Comment by Moonbase59** [comment]
> "Reset view" jumps not to the calculated, but a much larger area:

Rather odd now. Used:

````
```leaflet
id: route66
#lat: 37.6556
#long: -101.7334
#minZoom: 4
maxZoom: 18
#defaultZoom: 4.5
zoomDelta: 0.5
zoomFeatures: true
geojson: 
  #- [[geo-usa-route66-edit2.geojson]]
  - [[geo-bayern-landkreise.geojson]]
  - [[geo-lk-günzburg-gemeinden.geojson]]
```
````

- Ctrl-clicked on "Stadt Krumbach (Schwaben)" (real tiny) → correct display
- Click on "Reset view", got this:
  ![Auswahl_155](https://user-images.githubusercontent.com/3706922/122442199-99613880-cf9e-11eb-8c12-e82a524dc31f.png)



> "Current overlay" overlays everything until unfiltered, no access to overlays beneath.

Works on initial map display, _until_ …

- I unfilter "Current", and
- enable it again in the filter list.

**Comment by valentine195** [comment]
> Ctrl-clicked on "Stadt Krumbach (Schwaben)" (real tiny) → correct display
> Click on "Reset view", got this:

Using the files and map block you provided above, I did not experience this issue. Try restarting Obsidian?

>  Works on initial map display, until …

That makes sense - need to redraw the overlays unfortunately. Need to figure out a better way to do this without redrawing... let me think on it.

**Comment by Moonbase59** [comment]
Yep, I _did_ restart Obsidian—several times. Also closed/reopened the note the map is in, to be sure.

Yeah, we’re developing an ungodly speed here … don’t feel pressed, better really think a moment, test and take your time, then next test here.

**Comment by valentine195** [comment]
Okay, 3.18.6 should now sort overlays as they are added (without redrawing! 😁 )

**Comment by Moonbase59** [comment]
This change seems to work well, yay!

Now for the "Reset view"?

It looks to me that it finds the correct zoom factor but doesn’t pan to the correct center. Possible?

**Comment by valentine195** [comment]
Does reset view move there even if you _don't_ click on a feature?

**Comment by Moonbase59** [comment]
Yep.

**Comment by Moonbase59** [comment]
Could be there’s a typo or forgotten coordinate? Looks to me it gets zoom and left-right ok, only lacks up-down?

**Comment by valentine195** [comment]
I honestly have no idea what's happening. It _should_ be updating the `lat/long` correctly (and it is for me - Reset View correctly returns me to the initial map load with those GeoJSON files and the map block above).

https://github.com/valentine195/obsidian-leaflet-plugin/blob/370d72d56e3378c781610250c7f915f6754d6047/src/leaflet.ts#L546-L555

Are there any errors in the console? Maybe it's erroring before the update and not propagating.

**Comment by Moonbase59** [comment]
Hmmm. If it helps anyhow, I could offer an Anydesk session, and/or Jitsi for talking?

**Comment by valentine195** [comment]
Please try 3.18.8 and let me know if this still occurs.

If so, please use `verbose: true` in the map code block and let me know what the console shows.

**Comment by Moonbase59** [comment]
"Reset view" looks rather okay now. There is a minor shifting up between the initial view and an immediate "Reset view". Just a few pixels, no issue really.

No errors in console, Verbose log:

```text
Obsidian Leaflet Map route66: Building map instance.
utils.ts:31 Obsidian Leaflet Map route66: Beginning render process.
utils.ts:31 Obsidian Leaflet Map route66: Building initial map layer.
utils.ts:31 Obsidian Leaflet Map route66: MarkdownRenderChild loaded. Appending map.
utils.ts:31 Obsidian Leaflet Map route66: Moving to supplied coordinates: 51.133333,10.416667
utils.ts:31 Obsidian Leaflet Map route66: Adding markers to map.
utils.ts:31 Obsidian Leaflet Map route66: Adding overlays to map.
utils.ts:31 Obsidian Leaflet Map route66: Adding GeoJSON to map.
utils.ts:31 Obsidian Leaflet Map route66: Zooming to features.
utils.ts:31 Obsidian Leaflet Map route66: Features center: [48.91717417350914, 11.407755152134923]
utils.ts:31 Obsidian Leaflet Map route66: Initial map layer has rendered.
utils.ts:31 Obsidian Leaflet Map route66: Resetting map view to [48.91717417350914, 11.407755152134923].
```

**Comment by valentine195** [comment]
Great!

I believe it _was_ a race condition between the map moving and grabbing the map center. This made me realize I could just grab the feature center:

> EDIT: Oh, wait, you’re setting InitialCoords from the map, not from the combined center of the GeoJSON data. Could that be it? Then again, after a .fitBounds, the map should be ok, right?

**Comment by Moonbase59** [comment]
Playing with the "nearby" map and "Current" overlay: All good. Log:

```text
Obsidian Leaflet Map Main Map: Building map instance.
utils.ts:31 Obsidian Leaflet Map Main Map: Beginning render process.
utils.ts:31 Obsidian Leaflet Map Main Map: Building initial map layer.
utils.ts:31 Obsidian Leaflet Map Main Map: MarkdownRenderChild loaded. Appending map.
utils.ts:31 Obsidian Leaflet Map Main Map: Moving to supplied coordinates: 48.2418,10.3632
utils.ts:31 Obsidian Leaflet Map Main Map: Adding markers to map.
utils.ts:31 Obsidian Leaflet Map Main Map: Adding overlays to map.
utils.ts:31 Obsidian Leaflet Map Main Map: Adding GeoJSON to map.
utils.ts:31 Obsidian Leaflet Map Main Map: Initial map layer has rendered.
utils.ts:31 Obsidian Leaflet Map Main Map: Filtering out Current.
utils.ts:31 Obsidian Leaflet Map Main Map: Filtering in Current.
utils.ts:31 Obsidian Leaflet Map Main Map: Feature was Control clicked. Moving to bounds [48.02487067709069, 10.392324615763926]
utils.ts:31 Obsidian Leaflet Map Main Map: Resetting map view to [48.2418, 10.3632].
```

**Comment by Moonbase59** [comment]
Guess you made it, congrats!

**Comment by Moonbase59** [comment]
Interesting observation:

In one GeoJSON file, I have multiple features called "Hamburg" (because it’s not just the city, a small part of the sea also belongs to Hanburg), and it apparently makes these "one", i.e. Ctrl-clicking on _either_ "Hamburg" creates a map view that zooms so that _both_ "Hamburg" are to be seen. Perfect!

Hope this has no odd side effects on other possible GeoJSON data. I like it, only one might have to think about `name`, `title` and `description` properties again: I would say,

- a `name` should be unique per FeatureCollection; if not, all with the same name _can_ be aggregated like we see now,
- a `title` is usually just a bolded popup title (in other apps) and _can_ be used more than once, _without_ the features being aggregated,
- a `description` is just that—the text below a popup title
- for _Obsidian Leaflet_,
  - a `title`, if present, should have precedence over a `name`
  - a `name` should be used if a `title` is not present
  - if you want, you could display the `description`, if present, as text below the `name` or `title`

Just an idea. Again.

Like if someone would dumbly call all sections of a route `"title": "Section of Route 66"`, at least their names should be different (`"name": "section-2"`). We would then still be able to Ctrl-click the _sections_ (single features) but display "Section of Route 66" for all.

And if—just if—an extra `description` would exist, like `"description": "Extension of US 66 in 1937, upon completion of land reclamation for 1937 Chicago World's Fair"`, it _could_ display the title and this description below.

Provided that it doesn’t eat up all map space … Clicking on areas where tooltips appear can be unnerving because you don’t get there.

Thoughts?

**Comment by valentine195** [comment]
Here is the search order for popup text:

https://github.com/valentine195/obsidian-leaflet-plugin/blob/02bb33b11e651565167b93cfdd2202815b39f80a/src/leaflet.ts#L549-L552

Interesting behavior on the GeoJSON. That must be being done internally by Leaflet - I don't do any processing to the features outside of adding the styling.

**Comment by Moonbase59** [comment]
Yep, that’s why I didn’t suggest somehow displaying _all_ properties and their values in the first place (some apps do this).

How about:

- Auto-tooltipping (what a word!) only `title` or `name`, normal font. This would coincide with what we have.
- When simple left-click encountered on feature, display tooltip with _bold_ title/name and `description` below it?

**Comment by valentine195** [comment]
Would look like this: 
![image](https://user-images.githubusercontent.com/38669521/122463124-38783700-cf83-11eb-95ff-b47712628b1b.png)

Probably left align the description, though.

**Comment by Moonbase59** [comment]
Personally, I’m a "ragged-right" type, i.e. everything flush left.

I’d probably make the title bold, maybe a tad larger, left-justified, and the description normal font (not italics), left-justified.

**Comment by valentine195** [comment]
> When simple left-click encountered on feature, display tooltip with bold title/name and description below it? (Only if a description is present, otherwise just leave as is and only move to "here".)

I think I prefer just displaying it, if it is provided. 

Maybe make it a global / per-map setting.

**Comment by Moonbase59** [comment]
> I think I prefer just displaying it, if it is provided.

That would use up a lot of space on well-described data, making it real hard to click on something nearby, I’d think. Still your idea has the benefit of being easier for the user.

**Comment by Moonbase59** [comment]
Wikipedia, for example, don’t display anything _until you click on a feature_. Then their display is like this:

![U S  Route 66 - Wikipedia - Mozilla Firefox_156](https://user-images.githubusercontent.com/3706922/122465259-2cf33300-cfb8-11eb-948f-1b337e1ee05f.png)

**Comment by valentine195** [comment]
Makes sense, then. You've convinced me. 

Will implement tomorrow probably.

**Comment by Moonbase59** [comment]
I’m not infallible, just trying to think like a user. Maybe you implement it, and we simply use it for some days to see what the advantages/disadvantages are, hm?

Also, let’s invite @oyvindsolstad to let us know what he thinks.

**Comment by valentine195** [comment]
Added in 3.18.9. Play around with it and let me know how it looks.

**Comment by Moonbase59** [comment]
I would, only Obsidian tells me it has successfully updated from 3.18.8 and sticks with 3.18.8. Even after closing/reopening, it stays at 3.1.8 _but_ offers the update again and again …

**Comment by valentine195** [comment]
Not sure why the auto release didn't grab the updated one - it's correct in the `master` branch.

Just pushed 3.18.10, please try that.

**Comment by Moonbase59** [comment]
Testing, thanks …

**Comment by Moonbase59** [comment]
Now that I like! Showing the "info" icon is a neat idea, so one knows if it’s worth clicking!

Mind _not_ bolding the title if it’s showing the tooltip _without_ the description? The bold tooltips subconciously look "different" from the others, and one wonders why.

**Comment by valentine195** [comment]
Please try 3.18.11

**Comment by Moonbase59** [comment]
You bet! :grinning:

**Comment by Moonbase59** [comment]
I simply _love, love, love it!_

Time to close-close this issue, finally. :+1: :100:

**Comment by oyvindsolstad** [comment]
Seems like you solved it!

**Comment by Moonbase59** [comment]
How do _you_ like 3.18.11, @oyvindsolstad, for your purposes?

Too bad we’re "out of work" now, and have to go back to actually **using** the maps … :rofl: :rofl:
