### ISSUE TITLE
GeoJSON marker image source missing

### ISSUE THREAD

**Issue by Azulaloi** [valentine195/obsidian-leaflet-plugin#120]
When using GeoJSON data on an image map, the marker icon image for Point features is missing. 

The image element source is an image that does not exist: `<img src="app://obsidian.md/images/marker-icon-2x.png">`
In the devtools Sources tab, three missing icon images are requested from `/top/obsidian.md/images/`.

[Hastebin of JSON](https://hastebin.com/zubemibagu.json), [Map Block](https://hastebin.com/xicapesigu.yaml). Using plugin version `3.18.11`.

**Comment by valentine195** [comment]
This is also probably the case for a GeoJSON file in a real-world map. 

Happens because I cannot bundle Leaflet's static images with the plugin, so I'll need to intercept these. Thanks for letting me know.

**Comment by Azulaloi** [comment]
As a suggestion: it would be neat if this path could be configured or overwritten. Even neater would be to define it in the feature properties - maybe over a default path in the YAML, like with the fill/stroke/marker-color and geojsonColor.

**Comment by valentine195** [comment]
Would you rather that, or be able to set `marker-symbol` to a defined marker type from settings and have the plugin render an existing marker icon?

**Comment by Moonbase59** [comment]
I’d (of course) propose the defined marker symbols. Caveat: the "simplestyle" spec defines that it can only have [a-z0-9] (no uppercase), so either you’d have to forbid naming markers with blanks and uppercase and Unicode, or we’d simply ignore this part of the spec.

**Comment by valentine195** [comment]
You can use local images as marker icons, see [here](https://github.com/valentine195/obsidian-leaflet-plugin#using-an-image-as-a-marker-icon).

The plugin will now intercept "Point" features and use the marker icon defined in `marker-symbol` / the default marker icon if not provided.
