### ISSUE TITLE
GeoJSON "icon" property

### ISSUE THREAD

**Issue by Moonbase59** [valentine195/obsidian-leaflet-plugin#121]
Seems we opened a new can of worms with GeoJSON …

Converting some stored routes from Google Maps (hint: export as KML, use <https://mapbox.github.io/togeojson/> to convert to GeoJSON), I found that an "icon" property was included on all features (containg a Google URI). Leaflet seems to interpret "icon" somehow (or do _you_ use it internally?) – in any case, the map shows "broken link" images.

I wonder if we could make some sensible use of these.

Here’s a sample, converted like shown above:

```json
        {
            "type": "Feature",
            "geometry": {
                "type": "Point",
                "coordinates": [
                    10.3762215,
                    48.2389175,
                    0
                ]
            },
            "properties": {
                "name": "(My address)",
                "styleUrl": "#icon-1899-DB4436-nodesc",
                "styleHash": "39590fa4",
                "styleMapHash": {
                    "normal": "#icon-1899-DB4436-nodesc-normal",
                    "highlight": "#icon-1899-DB4436-nodesc-highlight"
                },
                "icon": "https://www.gstatic.com/mapspro/images/stock/503-wht-blank_maps.png"
            }
        }
```

And that’s what Leaflet makes of it:

![Auswahl_157](https://user-images.githubusercontent.com/3706922/122603115-30e48b00-d074-11eb-88b6-050e278781b6.png)

So I wonder

- does it _need_ a URI?
- could it be a defined map marker?
- a fontawesome symbol?
- if using a PNG, where to define the anchor?
- or should we simply strip "icon" from our GeoJSON files?

Did a quick check in the Leaflet docs, but didn’t really find anything useful.

**Comment by Moonbase59** [comment]
Here’s the console errors:

```text
marker-icon.png:1 GET app://obsidian.md/images/marker-icon.png net::ERR_FILE_NOT_FOUND
Image (async)
_createImg @ leaflet-src.js:7122
_createIcon @ leaflet-src.js:7089
createIcon @ leaflet-src.js:7070
_initIcon @ leaflet-src.js:7548
onAdd @ leaflet-src.js:7455
_layerAdd @ leaflet-src.js:6567
whenReady @ leaflet-src.js:4428
addLayer @ leaflet-src.js:6629
eachLayer @ leaflet-src.js:6856
onAdd @ leaflet-src.js:6840
_layerAdd @ leaflet-src.js:6567
whenReady @ leaflet-src.js:4428
addLayer @ leaflet-src.js:6629
eachLayer @ leaflet-src.js:6856
onAdd @ leaflet-src.js:6840
_layerAdd @ leaflet-src.js:6567
whenReady @ leaflet-src.js:4428
addLayer @ leaflet-src.js:6629
eachLayer @ leaflet-src.js:6856
onAdd @ leaflet-src.js:6840
_layerAdd @ leaflet-src.js:6567
whenReady @ leaflet-src.js:4428
addLayer @ leaflet-src.js:6629
addTo @ leaflet-src.js:6505
eval @ leaflet.ts:601
fulfilled @ tslib.es6.js:73
Promise.then (async)
step @ tslib.es6.js:75
eval @ tslib.es6.js:76
__awaiter @ tslib.es6.js:72
render @ leaflet.ts:388
eval @ leaflet.ts:91
eval @ tslib.es6.js:76
__awaiter @ tslib.es6.js:72
descriptor.value @ leaflet.ts:89
eval @ main.ts:609
fulfilled @ tslib.es6.js:73
Promise.then (async)
step @ tslib.es6.js:75
fulfilled @ tslib.es6.js:73
Promise.then (async)
step @ tslib.es6.js:75
fulfilled @ tslib.es6.js:73
Promise.then (async)
step @ tslib.es6.js:75
eval @ tslib.es6.js:76
__awaiter @ tslib.es6.js:72
postprocessor @ main.ts:130
(anonymous) @ app.js:1
t.postProcess @ app.js:1
t.postProcess @ app.js:1
h @ app.js:1
e.onRender @ app.js:1
requestAnimationFrame (async)
Be @ app.js:1
e.queueRender @ app.js:1
e.set @ app.js:1
t.set @ app.js:1
t.setViewData @ app.js:1
t.setData @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
s @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
o @ app.js:1
t.loadFileInternal @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
o @ app.js:1
t.onLoadFile @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
s @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
o @ app.js:1
t.loadFile @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
o @ app.js:1
t.setState @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
o @ app.js:1
t.setState @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
o @ app.js:1
t.setViewState @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
o @ app.js:1
t.openFile @ app.js:1
t.onFileClick @ app.js:1
s @ app.js:1
marker-shadow.png:1 GET app://obsidian.md/images/marker-shadow.png net::ERR_FILE_NOT_FOUND
Image (async)
_createImg @ leaflet-src.js:7122
_createIcon @ leaflet-src.js:7089
createShadow @ leaflet-src.js:7076
_initIcon @ leaflet-src.js:7582
onAdd @ leaflet-src.js:7455
_layerAdd @ leaflet-src.js:6567
whenReady @ leaflet-src.js:4428
addLayer @ leaflet-src.js:6629
eachLayer @ leaflet-src.js:6856
onAdd @ leaflet-src.js:6840
_layerAdd @ leaflet-src.js:6567
whenReady @ leaflet-src.js:4428
addLayer @ leaflet-src.js:6629
eachLayer @ leaflet-src.js:6856
onAdd @ leaflet-src.js:6840
_layerAdd @ leaflet-src.js:6567
whenReady @ leaflet-src.js:4428
addLayer @ leaflet-src.js:6629
eachLayer @ leaflet-src.js:6856
onAdd @ leaflet-src.js:6840
_layerAdd @ leaflet-src.js:6567
whenReady @ leaflet-src.js:4428
addLayer @ leaflet-src.js:6629
addTo @ leaflet-src.js:6505
eval @ leaflet.ts:601
fulfilled @ tslib.es6.js:73
Promise.then (async)
step @ tslib.es6.js:75
eval @ tslib.es6.js:76
__awaiter @ tslib.es6.js:72
render @ leaflet.ts:388
eval @ leaflet.ts:91
eval @ tslib.es6.js:76
__awaiter @ tslib.es6.js:72
descriptor.value @ leaflet.ts:89
eval @ main.ts:609
fulfilled @ tslib.es6.js:73
Promise.then (async)
step @ tslib.es6.js:75
fulfilled @ tslib.es6.js:73
Promise.then (async)
step @ tslib.es6.js:75
fulfilled @ tslib.es6.js:73
Promise.then (async)
step @ tslib.es6.js:75
eval @ tslib.es6.js:76
__awaiter @ tslib.es6.js:72
postprocessor @ main.ts:130
(anonymous) @ app.js:1
t.postProcess @ app.js:1
t.postProcess @ app.js:1
h @ app.js:1
e.onRender @ app.js:1
requestAnimationFrame (async)
Be @ app.js:1
e.queueRender @ app.js:1
e.set @ app.js:1
t.set @ app.js:1
t.setViewData @ app.js:1
t.setData @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
s @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
o @ app.js:1
t.loadFileInternal @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
o @ app.js:1
t.onLoadFile @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
s @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
o @ app.js:1
t.loadFile @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
o @ app.js:1
t.setState @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
o @ app.js:1
t.setState @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
o @ app.js:1
t.setViewState @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
o @ app.js:1
t.openFile @ app.js:1
t.onFileClick @ app.js:1
s @ app.js:1
```

**Comment by valentine195** [comment]
> Leaflet seems to interpret "icon" somehow (or do you use it internally?)

Nope, this is something Leaflet is doing. Almost certainly the same issue as #120.

**Comment by Moonbase59** [comment]
Yeah, I thought so.

**Comment by Moonbase59** [comment]
Hm. Maybe there is some way to override the Leaflet image locations and store them within your plugin data space?

**Comment by valentine195** [comment]
I actually used to do that for the "layer" control box image, but its unwieldy and hacky. I'll just intercept Point features and load a default marker icon unless `marker-symbol` is provided.

**Comment by Moonbase59** [comment]
I wondered if maybe `L.Icon.Default.imagePath` could be overridden …

**Comment by valentine195** [comment]
Yes, one of the defined names. It will just place that exact icon as defined in settings at the point. If it can't find it, it will just place the default marker symbol. I think it would probably not be possible to support the entire range of symbols such as those.

**Comment by Moonbase59** [comment]
No, certainly not, I agree, just checked OSM wiki. The defined are good enough. If anyone wants a "bus", go declare it in settings. ;-)

But we _are_ willing to intentionally break simplespec here, right?

**Comment by valentine195** [comment]
Yes, especially since for the most part users will have to break it intentionally in order to get a marker symbol they have defined.

**Comment by Moonbase59** [comment]
Yup. Good decision.

**Comment by Moonbase59** [comment]
Oops. Just read the simplespec again: It apparently uses a "default marker", and `marker-symbol` (if not "") is supposed to be _overlaid_ to that. Much like your default marker + the fa icons. Plus, it has `marker-color`.

> a symbol to position in the center of this icon if not provided or "", no symbol is overlaid and only the marker is shown

I wonder if it would make more sense then to use the default marker, take up the default marker color from settings, and allow specifying _any_ supported fa icon to be put "into" the default marker (like with your settings)?

On the one side, this would be more flexible (and better adhere to the simplespec), on the other side, you’d have to redefine the markers yourself (i.e. symbol & color). Both has pros and cons.

**Comment by Azulaloi** [comment]
I agree about filter list length - too many marker presets quickly gets out of hand. Maybe being able to define an icon per-marker, without a preset, would help without necessitating a complex preset management system.

The FA icons are okay, but I like using custom images. Being able to use a local (or web) image without a preset for each would be ideal for my use case. This goes for both GeoJSON and the normal markers.

**Comment by valentine195** [comment]
You can use local images as marker icons, see [here](https://github.com/valentine195/obsidian-leaflet-plugin#using-an-image-as-a-marker-icon).

The plugin will now intercept "Point" features and use the marker icon defined in `marker-symbol` / the default marker icon if not provided.

**Comment by Azulaloi** [comment]
I know local images can be used, my suggestion was as a solution for the 'predefined custom markers list becoming too large' issue that Moonbase mentioned. 

I think I've found a bug in the new build, I'll make an issue for it shortly.
