### ISSUE TITLE
GeoJSON: Map doesn’t zoom to features, only after code block change

### ISSUE THREAD

**Issue by Moonbase59** [valentine195/obsidian-leaflet-plugin#126]
I have a map for a small educational trail nearby (GIEP, Gewässer-Informations-Erlebnis-Pfad Münsterhausen), which for some reason doesn’t zoom to features when the note is opened. Only after manually changing the code block, then switching back to preview mode, it is displayed correctly.

When closing and re-opening the note, it is back to not zooming in again.

### How it looks

![Auswahl_027](https://user-images.githubusercontent.com/3706922/122678075-74aad200-d1e5-11eb-9ce3-c2fae87affb8.png)

### The map

````
### Karte

```leaflet
id: GIEP
maxZoom: 18
#defaultZoom: 4.5
#zoomDelta: 0.5
zoomFeatures: true
geojson: 
  - [[Gewässer-Informations-Erlebnis-Pfad Münsterhausen.geojson]]
verbose: true
```
````

### The GeoJSON

[Gewässer-Informations-Erlebnis-Pfad Münsterhausen.geojson.zip](https://github.com/valentine195/obsidian-leaflet-plugin/files/6682523/Gewasser-Informations-Erlebnis-Pfad.Munsterhausen.geojson.zip)

_Note:_ Needs map markers `Recreation` and `Sight` to be available.

### "Verbose" messages upon initial opening

```text
utils.ts:31 Obsidian Leaflet Map GIEP: Building map instance.
utils.ts:31 Obsidian Leaflet Map GIEP: Beginning render process.
utils.ts:31 Obsidian Leaflet Map GIEP: Building initial map layer.
utils.ts:31 Obsidian Leaflet Map GIEP: MarkdownRenderChild loaded. Appending map.
utils.ts:31 Obsidian Leaflet Map GIEP: Moving to supplied coordinates: 51.133333,10.416667
utils.ts:31 Obsidian Leaflet Map GIEP: Adding markers to map.
utils.ts:31 Obsidian Leaflet Map GIEP: Adding overlays to map.
utils.ts:31 Obsidian Leaflet Map GIEP: Adding GeoJSON to map.
utils.ts:31 Obsidian Leaflet Map GIEP: Zooming to features.
utils.ts:31 Obsidian Leaflet Map GIEP: Features center: [48.31015, 10.45135]
utils.ts:31 Obsidian Leaflet Map GIEP: Initial map layer has rendered.
```

### "Verbose" after changing the code block (changed `maxZoom` from `18` to `17`):

```text
utils.ts:31 Obsidian Leaflet Map GIEP: Building map instance.
utils.ts:31 Obsidian Leaflet Map GIEP: Beginning render process.
utils.ts:31 Obsidian Leaflet Map GIEP: Building initial map layer.
utils.ts:31 Obsidian Leaflet Map GIEP: MarkdownRenderChild loaded. Appending map.
utils.ts:31 Obsidian Leaflet Map GIEP: Moving to supplied coordinates: 51.133333,10.416667
utils.ts:31 Obsidian Leaflet Map GIEP: Adding markers to map.
utils.ts:31 Obsidian Leaflet Map GIEP: Adding overlays to map.
utils.ts:31 Obsidian Leaflet Map GIEP: Adding GeoJSON to map.
utils.ts:31 Obsidian Leaflet Map GIEP: Zooming to features.
utils.ts:31 Obsidian Leaflet Map GIEP: Features center: [48.31015, 10.45135]
utils.ts:31 Obsidian Leaflet Map GIEP: Initial map layer has rendered.
```

### Display after changing the code block (changed `maxZoom` from `18` to `17`):

![Auswahl_028](https://user-images.githubusercontent.com/3706922/122678238-33ff8880-d1e6-11eb-8501-0acce9c3c8dc.png)

**Comment by valentine195** [comment]
At maxZoom: 18, can you manually zoom to that same view?

**Comment by Moonbase59** [comment]
Yep, to that view and further in (up to 18):

![Auswahl_029](https://user-images.githubusercontent.com/3706922/122679731-4977b100-d1ec-11eb-9b07-955e0906dbf1.png)

Cheers for checking!

**Comment by valentine195** [comment]
Hmm... does this issue still occur?

Not seeing it on my end.

**Comment by Moonbase59** [comment]
I was about to say "no", but _one_ small change (`maxZoom: 18` → `maxZoom: 17`) brought it up again.

**Comment by valentine195** [comment]
Interesting...

I'll keep this open, but I copied your map / geojson file and it works for me.

````
```leaflet
id: GIEP
maxZoom: 18
#defaultZoom: 4.5
#zoomDelta: 0.5
zoomFeatures: true
geojson: 
  - [[Gewässer-Informations-Erlebnis-Pfad Münsterhausen.geojson]]
verbose: true
```
````

https://www.loom.com/share/73365ae2ec6b4276b0722079e519abbc

**Comment by Moonbase59** [comment]
Loom: `An error occurred on the page: ReferenceError: ResiteObserver is not defined`

Tried it on another machine: Same result, shows "whole world" on initial opening, after changing `maxZoom` works:

```text
app.js:1 Obsidian Developer Console
main.ts:25 Loading Pandoc plugin
main.ts:32 loading PomodoroTimerPlugin
main.ts:73 Loading Obsidian Leaflet v3.18.14
main.ts:27 loading markdown-table-editor plugin
main.ts:35 Dataview: Version 0.3.x Loaded
main.ts:49 loading Find unlinked files and unresolved links plugin
main.ts:40 loading Hotkeys for templates plugin v1.4.1
main.ts:10 Loading Hotkeys++ plugin
main.ts:125 loading plugin
main.ts:40 loading sortable plugin
main.ts:17 Loading snippets plugin
main.ts:45 loading plugin
index.ts:344 Dataview: Parsed all file prefixes (0.002s)
main.ts:148 Hotkeys for templates -> active plugins: templater-obsidian,core
index.ts:206 Dataview: Task & metadata parsing queued in 0.001s.
utils.ts:31 Obsidian Leaflet Map GIEP: Building map instance.
utils.ts:31 Obsidian Leaflet Map GIEP: Beginning render process.
utils.ts:31 Obsidian Leaflet Map GIEP: Building initial map layer.
utils.ts:31 Obsidian Leaflet Map GIEP: MarkdownRenderChild loaded. Appending map.
utils.ts:31 Obsidian Leaflet Map GIEP: Moving to supplied coordinates: 51.133333,10.416667
utils.ts:31 Obsidian Leaflet Map GIEP: Adding markers to map.
utils.ts:31 Obsidian Leaflet Map GIEP: Adding overlays to map.
utils.ts:31 Obsidian Leaflet Map GIEP: Adding GeoJSON to map.
utils.ts:31 Obsidian Leaflet Map GIEP: Zooming to features.
utils.ts:31 Obsidian Leaflet Map GIEP: Features center: [48.31015, 10.45135]
utils.ts:31 Obsidian Leaflet Map GIEP: Initial map layer has rendered.
utils.ts:31 Obsidian Leaflet Map GIEP: Building map instance.
utils.ts:31 Obsidian Leaflet Map GIEP: Beginning render process.
utils.ts:31 Obsidian Leaflet Map GIEP: Building initial map layer.
utils.ts:31 Obsidian Leaflet Map GIEP: MarkdownRenderChild loaded. Appending map.
utils.ts:31 Obsidian Leaflet Map GIEP: Moving to supplied coordinates: 51.133333,10.416667
utils.ts:31 Obsidian Leaflet Map GIEP: Adding markers to map.
utils.ts:31 Obsidian Leaflet Map GIEP: Adding overlays to map.
utils.ts:31 Obsidian Leaflet Map GIEP: Adding GeoJSON to map.
utils.ts:31 Obsidian Leaflet Map GIEP: Zooming to features.
utils.ts:31 Obsidian Leaflet Map GIEP: Features center: [48.31015, 10.45135]
utils.ts:31 Obsidian Leaflet Map GIEP: Initial map layer has rendered.
```

Log shows initial loading plus loading after changing `maxZoom`.

**Comment by valentine195** [comment]
Could you try on 3.19.0? I wonder if I unintentionally fixed it.

**Comment by Moonbase59** [comment]
Yup, you actually gave me a _lot_ to test, considering all the closed issues. Testing all of them again may take a while, will try to do most/all tomorrow.

**Comment by valentine195** [comment]
No worries, and thank you so much for the extensive testing - it really made this plugin what it is 😃

**Comment by Moonbase59** [comment]
Ditto for listening and going along :-)

This one is unfortunately still going wrong. Changing the code block makes it work _as long as you stay in the note_, but when closing/reopening it shows the "world" map again.

**Comment by Moonbase59** [comment]
Still the same in 3.19.1.

**Comment by Moonbase59** [comment]
Still exists in 3.19.7. Any ideas on this one before you take a break? +smile+

**Comment by valentine195** [comment]
Does the map actually move to the feature center, but not zoom?

**Comment by Moonbase59** [comment]
I’d say (visually) it moves to the feature center, but when I manually zoom in and Ctrl+Click the GeoJSON, coordinates are slightly different. Reset view resets to "world size":

```text
app.js:1 Obsidian Developer Console
main.ts:25 Loading Pandoc plugin
main.ts:32 loading PomodoroTimerPlugin
VM125:2 Loading Obsidian Leaflet v3.19.7
main.ts:27 loading markdown-table-editor plugin
main.ts:38 Dataview: Version 0.4.x Loaded
main.ts:49 loading Find unlinked files and unresolved links plugin
main.ts:40 loading Hotkeys for templates plugin v1.4.1
main.ts:10 Loading Hotkeys++ plugin
main.ts:125 loading plugin
main.ts:40 loading sortable plugin
main.ts:17 Loading snippets plugin
main.ts:45 loading plugin
index.ts:351 Dataview: Parsed all file prefixes (0.001s)
main.ts:148 Hotkeys for templates -> active plugins: templater-obsidian,core
index.ts:242 Dataview: Task & metadata parsing queued in 0.001s.
VM125:2 Obsidian Leaflet Map GIEP: Building map instance.
VM125:2 Obsidian Leaflet Map GIEP: Beginning render process.
VM125:2 Obsidian Leaflet Map GIEP: Building initial map layer.
VM125:2 Obsidian Leaflet Map GIEP: MarkdownRenderChild loaded. Appending map.
VM125:2 Obsidian Leaflet Map GIEP: Moving to supplied coordinates: 51.133333,10.416667
VM125:2 Obsidian Leaflet Map GIEP: Adding 1 GeoJSON features to map.
VM125:2 Obsidian Leaflet Map GIEP: 1 GeoJSON feature added to map.
VM125:2 Obsidian Leaflet Map GIEP: Zooming to features.
VM125:2 Obsidian Leaflet Map GIEP: Features center: [48.31015, 10.45135]
VM125:2 Obsidian Leaflet Map GIEP: Initial map layer rendered in 0.621 seconds.
VM125:2 Obsidian Leaflet Map GIEP: Feature was Control clicked. Moving to bounds [48.30936520405449, 10.45147955417633]
VM125:2 Obsidian Leaflet Map GIEP: Resetting map view to [48.31015, 10.45135].
```

Maybe we could add the zoom level to the "verbose" output?

**Comment by valentine195** [comment]
Yeah, that log is meant as "I _should_ zoom" not "I _am_ zooming".

**Comment by Moonbase59** [comment]
And yes, it moves to feature center but doesn’t zoom (tried with some wild `lat:` and `long:` values).

**Comment by valentine195** [comment]
Okay, interesting, thanks.

**Comment by Moonbase59** [comment]
I wonder if this could be a timing issue: This note has a 4.8 MB image to load above the map. When I comment that out (or change it to a link instead of image embed), the map seems to work!

For you to possibly reproduce:

````
---
#location: [48.323380433488, 10.443368000767947] # Start Nord
location: [48.2969, 10.459] # Start Süd
mapmarker: Check
# The map overlay shows 11 stations of an educational nature trail
mapoverlay:
  - ['rgba(192, 0, 192, .6)', [48.2969, 10.459], 5 m, "GIEP Startpunkt Süd"]
  - ['rgba(192, 0, 192, .6)', [48.301, 10.4565], 5 m, "GIEP 1. Kanal und Wehr, Fischtreppe"]
  - ['rgba(192, 0, 192, .6)', [48.3061, 10.4542], 5 m, "GIEP 2. Fischregionen, Heimische Fische"]
  - ['rgba(192, 0, 192, .6)', [48.3072, 10.4487], 5 m, "GIEP 3. Ausgleichsfläche, Amphibien, Vegetation Kühgraben"]
  - ['rgba(192, 0, 192, .6)', [48.3118, 10.4463], 5 m, "GIEP 4. Element Wasser, Spielplatz"]
  - ['rgba(192, 0, 192, .6)', [48.3131, 10.4495], 5 m, "GIEP 5. Wasservögel, Hochwasser"]
  - ['rgba(192, 0, 192, .6)', [48.314, 10.449], 5 m, "GIEP 6. Uferbegleitvegetation"]
  - ['rgba(192, 0, 192, .6)', [48.3163, 10.4474], 5 m, "GIEP 7. Wasserkraft, Mühlengeschichte"]
  - ['rgba(192, 0, 192, .6)', [48.3193, 10.4481], 5 m, "GIEP 8. Weißstorch"]
  - ['rgba(192, 0, 192, .6)', [48.3188, 10.4458], 5 m, "GIEP 9. Kiesabbau"]
  - ['rgba(192, 0, 192, .6)', [48.3192, 10.4455], 5 m, "GIEP 10. Biber"]
  - ['rgba(192, 0, 192, .6)', [48.3216, 10.4441], 5 m, "GIEP 11. Naturraum Mindeltal"]
  - ['rgba(192, 0, 192, .6)', [48.3234, 10.4437], 5 m, "GIEP Startpunkt Nord"]
tags: check, location, recreation, walking, lehrpfad, trail, map
#nearby: 2 km
---

[[-Locations TOC]] [[-Map]] `= elink("https://www.google.com/maps/search/?api=1&query=" + this.location[0] + "," + this.location[1], "Google Maps")` `= elink("https://www.google.com/maps/@?api=1&map_action=pano&viewpoint=" + this.location[0] + "," + this.location[1], "Street View")` `= elink("https://www.google.com/maps/dir/?api=1&dir_action=navigate&destination=" + this.location[0] + "," + this.location[1], "Route")`

---

# ![[Check.svg]] ![[Recreation.svg]] Gewässer-Informations-Erlebnis-Pfad Münsterhausen

86505 Münsterhausen

![[Gewässer-Informations-Erlebnis-Pfad Münsterhausen Karte.png]]

### Erlebnispfad mit 11 Stationen

Die rund 5 km lange Route entlang der [[Mindel]] verläuft größtenteil auf dem Mindeltal-Radweg, ermöglicht aber auch Abstecher zu abseits gelegenen, interessanten Wasserorten, an denen Wasser erforscht sowie erlebt werden kann.  
  
An 11 Stationen werden anhand von Informationstafeln verschiedene Facetten des Lebens an und in den Gewässern Münsterhausens gezeigt. Der Lehrpfad soll naturkundliches Wissen vermitteln, zum Nachdenken anregen und letztlich einen behutsamen Umgang mit unserem Lebensraum fördern.

#### Stationen

1. Kanal und Wehr, Fischtreppe
2. Fischregionen, Heimische Fische
3. Ausgleichsfläche, Amphibien, Vegetation Kühgraben
4. Element Wasser, Spielplatz
5. Wasservögel, Hochwasser
6. Uferbegleitvegetation
7. Wasserkraft, Mühlengeschichte
8. Weißstorch
9. Kiesabbau
10. Biber
11. Naturraum Mindeltal

### Karte

```leaflet
id: GIEP
maxZoom: 18
#defaultZoom: 4.5
#zoomDelta: 0.5
zoomFeatures: true
geojson: 
  - [[Gewässer-Informations-Erlebnis-Pfad Münsterhausen.geojson]]
verbose: true
```

---

Gefunden auf <https://www.familien-und-kinderregion.de/poi/giep-gewaesser-informations-erlebnispfad>.

````

The files used:

[GIEP-data.zip](https://github.com/valentine195/obsidian-leaflet-plugin/files/6817831/GIEP-data.zip)

**Comment by Moonbase59** [comment]
Seems rather reproducable: Change image embed to link or vice versa, close/reopen note and it will show/not show the zoomed-in map. Tested on 2 machines.

**Comment by valentine195** [comment]
yeah happens on my end too. Interesting. Now that I can reproduce it, though, I can fix it! (hopefully...)

**Comment by Moonbase59** [comment]
Great! (Hopefully :grin: )

**Comment by Moonbase59** [comment]
If it wasn’t the time to load the image, could also be the name? They’re named identically, except for the file extension.

**Comment by valentine195** [comment]
No, it shouldn't be - the plugin uses Obsidian's file system adapter, which takes extensions into account.

**Comment by Moonbase59** [comment]
I wonder if one has to wait for something like "DOM stable" or "DOM fully loaded" …

**Comment by Moonbase59** [comment]
I read somewhere: "Generally, you need to check workspace.layoutReady 13 and only register for the event if it’s false. If the layout is already ready, registering for the event won’t do much."

**Comment by valentine195** [comment]
Possibly, but I would've thought that would be taken care of by the `MarkdownRenderChild` loading. 🤷🏼 I believe that the `layoutReady` event is just to know when the overall workspace itself has been fully loaded, not an individual note.

It seems to be breaking if either the image or the SVGs are embedded. I may need to ask on the obsidian discord for some ideas on how to fix this one.

**Comment by Moonbase59** [comment]
As a reference, I found it mentioned

- https://forum.obsidian.md/t/obsidian-api-layout-ready-and-layout-change-events/11502
- https://github.com/obsidianmd/obsidian-api/blob/b0aa06eab03d8c39c0733949da5aa1edc2084b01/obsidian.d.ts#L3221

**Comment by Moonbase59** [comment]
I was assuming that, too (complete layout ready), and that we only get the event upon initial Obsidian startup. But who knows …

**Comment by valentine195** [comment]
What's interesting is it _doesn't_ seem to be a timing issue. The leaflet `getBoundsZoom()` function returns 1 even if I call it a full 10 seconds after the map has rendered.

It makes sense that editing the code block fixes it, though, because Obsidian only re-parses changed Markdown blocks, so the images do not get reloaded.

**Comment by Moonbase59** [comment]
Hm. Two ideas here:

- either getBoundsZoom() evaluates some zoom level that isn’t within minZoom .. maxZoom, or
- need to `invalidateSize()` somewhere?

**Comment by valentine195** [comment]
Possibly. Going through leaflet's source, I have tracked down what is happening, but not why yet (and it seems to be something with Obsidian). The container size is zero, so when the map tries to calculate the zoom (using the scale, which uses the container size...) it gets -Infinity, which they resolve to 1. So it zooms to 1, which is the world.

**Comment by Moonbase59** [comment]
Hm. Container size zero (with images) usually means they’re not completely loaded yet (from experience with a 181 MB NASA earth image).

**Comment by valentine195** [comment]
Right... but it happens even if I put the call on a timeout.

Also, oddly enough, if you move the map block on the page, it works (such as above or below the image).

**Comment by valentine195** [comment]
I figured it out.

Obsidian dynamically loads elements depending on how close they are to the view port. The image pushes the map element outside of the range, which causes it to be unloaded from the DOM (and therefore have no size).

I'll see if there's a way to detect the element being loaded.

**Comment by Moonbase59** [comment]
Now that’s an interesting find! Good that I had this rather vertical image, by chance.

In general, this would mean Obsidian handles large, long files rather efficiently. I’ve had some issues with Markdown preview horribly slowing down things in Atom (another Electron editor), maybe Obsidian will perform better in such circumstances.

This also means all codeblock-content plugins need to be aware they could be unloaded/loaded almost anytime. Well, as long as we know it … Might slow down hires image maps, though.

**Comment by valentine195** [comment]
Mostly this only affects Leaflet because it relies so much on the container size to calculate things, which can be zero if it is not loaded initially. I would say _most_ other plugins would be fine.

**Comment by Moonbase59** [comment]
It’s only bad that we have to second-guess all these internals … There are times I sincerely wish Obsidian would be open source.

**Comment by valentine195** [comment]
Okay, I pushed an update to the repository that fixes this but I want to do more testing & wait to see if someone on the discord has a better idea how to do it before pushing a new release.

**Comment by Moonbase59** [comment]
Yep, ok. I’ll be interested in your findings, as always.
