### ISSUE TITLE
Multiple map layers with ability to toggle between them

### ISSUE THREAD

**Issue by graemehousego** [valentine195/obsidian-leaflet-plugin#13]
Not sure the extent of leaflet's capabilities but being able to have multiple maps overlaid on top of one another would be beneficial, especially things like dungeon maps as you would be able to overlay different dungeon levels on top of one another.  I suppose it would be on the user to ensure their images are of similar size.

**Comment by valentine195** [comment]
This is definitely possible. If you want to change map layers, I could just replace the current image being shown, and maybe have a list of layers on the left under the zoom controls?

I don't think there would be any sizing issues, but the maps would default to being anchored in their center points.

Possible syntax?
`markdown
```leaflet
image: a.jpg
image: b.jpg
image: c.jpg
```
`

And this would layer a on top of b on top of c.

**Comment by graemehousego** [comment]
Would you be able to do different pins/pin locations on the different layers?

**Comment by valentine195** [comment]
Yes, definitely. 

Since I'll have a layer control box, I'm also adding the ability to turn off marker groups (the different marker types defined in settings), because that's pretty easy to do simultaneously.

**Comment by graemehousego** [comment]
Awesome, sounds like a good plan

**Comment by valentine195** [comment]
Just added this. It shouldn't break your current marker placements, but I would make a backup of your data.json file before updating just in case.
