### ISSUE TITLE
Issues with marker controls

### ISSUE THREAD

**Issue by valentine195** [valentine195/obsidian-leaflet-plugin#136]
Deleting/re-adding works fine now, only the moment I add the first marker, "Reset view" and "Show all markers" swap places.

Also, if I filter all marker(s) out, "show all markers" stays clickable (not grayed).
Double tooltips also still there.

When deleting all markers, filter is still enabled but bulk edit grayed. Should be the other way round, I think.

If you hit the (disabled) "Show all markers" a few times in succession, notifications are shown and the map starts zooming. Same with "Reset view" button, if you hit it fast enough. And the bulk edit, if it’s disabled.

I suppose this is some "hidden" Leaflet feature: double-click in the map and it’ll zoom in one step. Yep, verified on online Leaflet maps.

Q: Is it possible, for a "grayed" button, to _not_ pass through mouse clicks and drags?

Also interesting: If you drag the "+" or "-" buttons, they create a default marker linked to "app://obsidian.md/index.html#". Same for the "Filter" button, but not the others. Huh?

_Originally posted by @Moonbase59 in https://github.com/valentine195/obsidian-leaflet-plugin/issues/123#issuecomment-864327386_

**Comment by Moonbase59** [comment]
Seems fixed in 3.19.0.
