### ISSUE TITLE
Initial location not working for SVG and img files

### ISSUE THREAD

**Issue by VictorGrycuk** [valentine195/obsidian-leaflet-plugin#138]
Hi, thanks for the plugin, I found it super helpful.
However, when using svg or an image as source, the initial location is not working. I am not sure if it's an error on my configuration or it simply it's not supported on these kinds of source.

This is an example of a configuration I have. The `lat` and `long` were obtained placing a marker on my desired initial position. It always reset to the top left corner.

```leaflet
id: ankh-morpork-map
image: [[ankh-morpork-map.png]]
lat: -3.60528564453125
long: 4.556640625
defaultZoom: 9
scale: 5400
```

Please let me know if I can provide any other useful information that might help solve this.
Thanks.

**Comment by valentine195** [comment]
Ah, this is something that I need to update. There's a lot of issues relating to image map coordinates.

Currently, you have to specify the initiatl lat/long of an image map as _a percentage distance from the top left corner_.

I will update this to only parse these as percentages if it is supplied as a percentage string (aka with a %). I haven't had much time to work on the plugin recently, though.

**Comment by VictorGrycuk** [comment]
I just tried using percentages, and yes it works!
Thank you for the help, I will close the issue.
