### ISSUE TITLE
Add ability to bulk add / edit markers

### ISSUE THREAD

**Issue by valentine195** [valentine195/obsidian-leaflet-plugin#14]

**Comment by timjore** [comment]
Connected to this, I would like to be able to have easy access to the actual marker data, including marker type, linked note, long/lat, etc. This will make it easier to bulk import/export/edit the data. Perhaps marker data could be stored in in a separate file in Obsidian, a Markdown table, an embedded CSV, e.g., 

```leaflet-data
Linked Note 1, Marker1, 12.3456, -23.4567
Linked Note 2, Marker1, 12.4567, -23.5678
...
```

**Comment by valentine195** [comment]
All of the marker data is stored in the data.json file in the plugin folder - or do you mean easier access?

**Comment by Moonbase59** [comment]
Currently looks like this here (Obsidian 0.12.3, Obsidian Leaflet 3.8.1):

![obsidian-leaflet-bulk-edit](https://user-images.githubusercontent.com/3706922/118112885-e2453080-b3e5-11eb-91f9-a7b824661b93.png)

**Comment by valentine195** [comment]
Whoops, this wasn't meant to be included in this release.
