### ISSUE TITLE
Improve marker note-target UI

### ISSUE THREAD

**Issue by valentine195** [valentine195/obsidian-leaflet-plugin#15]
- [x] Only require name of file (remove folders and file-extension requirement)
- [x] Add auto-completion / suggestions as file name is typed
- [x] _Possibly:_ Select note from dropdown?

Merges with #16

**Comment by timjore** [comment]
Great plugin, thanks! 

In addition to the "remove .md requirement":
- [ ] when naming a marker, I would like to be presented with an auto-fill list of available notes from which to choose.
- [ ] from the note selection interface, I would like to be able to enter a name for a note that does not yet exist and create the new note when the marker is clicked

**Comment by valentine195** [comment]
Yeah, I was planning on adding the autocomplete / list of notes (should probably merge this issue with #16 as a broader "Redo Marker Note Target" issue). 

> from the note selection interface, I would like to be able to enter a name for a note that does not yet exist and create the new note when the marker is clicked

I believe the plug-in should already do this if you put in the path to a note that does not exist.

I'm not sure if it would create the note in the correct folder. Worth a shot?

**Comment by valentine195** [comment]
Version 2.0.0 closes this issue.
