### ISSUE TITLE
3.19.0: Existing markers in map not shown, only after bulk edit & save

### ISSUE THREAD

**Issue by Moonbase59** [valentine195/obsidian-leaflet-plugin#150]
The new version displays GeoJSON ok, but on initial map view of an existing map, existing markers set on the map aren’t shown. If I enter "bulk edit", these are shown, and if I save again, they appear. When I close/reopen the note, the markers are gone again.

The map:

````
```leaflet
id: Middle Earth
# the image is 1600x1200 px
image:
  - [[middle-earth-map.jpg]]
  - [[middle-earth-map-paths.jpg]]
# bounds uses y,x (CRS.Simple?)
#bounds: [[0,0], [1200, 1600]]
# bounds in miles (as per map scale: 100 mi = 85 px)
bounds: [[0,0], [1411.76, 1882.35]]
# after this, southwest = 0,0; northeast = 1411.76, 1882.35
height: 500px
# lat/long in percent doesn’t center
# does ist not respect scale or bounds?
# would be easier if this was a coordinate in "bounds" range,
# as the "final" coordinates will be.
lat: 50
long: 50
minZoom: -2
maxZoom: 1
defaultZoom: -1
unit: miles
#scale: 1.176470588  # 1/0.85
scale: 1
# make check markers in the center, SW, NE (y,x in "bounds" coordinates)
# (in the middle of Fangorn!)
marker: Current, 705.88, 941.175
#overlay: [[red, [705.88, 941.175], 100 miles, "Test Overlay"]]
# Southwest (0,0)
marker: Check, 0, 0
# Northeast (1411.76, 1882.35)
marker: Check, 1411.76, 1882.35
geojson:
    - [[geo-fangorn.geojson]]
    - [[geo-line.geojson]]
#markerFile: [[Elvenking’s Halls]]
#markerFolder: Testing
markerTag: middleearth 
verbose: true
```
````

Display (zoomed out to see all markers):

![Auswahl_040](https://user-images.githubusercontent.com/3706922/125071072-1b81e000-e0b9-11eb-95f4-a25828d543d0.png)

Bulk edit & save:

![Auswahl_041](https://user-images.githubusercontent.com/3706922/125071101-250b4800-e0b9-11eb-95a8-d25189d76db1.png)

Markers reappear (until closing/reopening the map note):

![Auswahl_042](https://user-images.githubusercontent.com/3706922/125071181-3f452600-e0b9-11eb-8be2-45ce304caff3.png)

Console:

```text
utils.ts:31 Obsidian Leaflet Map Middle Earth: Building map instance.
utils.ts:31 Obsidian Leaflet Map Middle Earth: Beginning render process.
utils.ts:31 Obsidian Leaflet Map Middle Earth: Building initial map layer.
utils.ts:31 Obsidian Leaflet Map Middle Earth: MarkdownRenderChild loaded. Appending map.
utils.ts:31 Obsidian Leaflet Map Middle Earth: Moving to supplied coordinates: 50,50
utils.ts:31 Obsidian Leaflet Map Middle Earth: Adding markers to map.
utils.ts:31 Obsidian Leaflet Map Middle Earth: Adding overlays to map.
utils.ts:31 Obsidian Leaflet Map Middle Earth: Adding GeoJSON to map.
utils.ts:31 Obsidian Leaflet Map Middle Earth: Initial map layer has rendered.
utils.ts:31 Obsidian Leaflet Map Middle Earth: Building additional map layers in background.
utils.ts:31 Obsidian Leaflet Map Middle Earth: Moving to display 4 markers.
```

**Comment by valentine195** [comment]
I can't recreate this one. Is it still happening?

**Comment by Moonbase59** [comment]
Yep, still happens with 3.19.1.

**Comment by valentine195** [comment]
Okay, I've been tinkering and _just_ got it to reproduce. Will work on a fix, thanks

**Comment by Moonbase59** [comment]
Thank _you_!

**Comment by valentine195** [comment]
Are the markers that disappear on your second layer?

**Comment by Moonbase59** [comment]
No, on the first. The second was only for testing and can be removed—behaviour stays the same.

**Comment by valentine195** [comment]
Hmm, I don't _think_ so (but you never know 😁 ) - I think it could be a weird side effect of the different map layers, because the Bulk Edit modal wasn't differentiating between layers when adding markers, so they were all being shown.

**Comment by Moonbase59** [comment]
Yup, getting all these layers correct each and every time might get complicated …

**Comment by valentine195** [comment]
Is this still occurring? I suddenly can't reproduce it.

**Comment by Moonbase59** [comment]
Yeah it does. Probably some change in between versions, and the newer version not picking up the old data correctly. It _can_ be fixed by simply deleting all old markers and adding new ones, though. (Which will stay.)

**Comment by valentine195** [comment]
Okay, that's why then - I completely re-installed the plugin, which removed the data file. Thanks!

**Comment by Moonbase59** [comment]
I wonder if we could say this was an "unfortunate side-effect", because I don’t believe many people will have been hit by it. What do you think, close it and concentrate on other stuff?

**Comment by valentine195** [comment]
Hmm, I think I actually do know what's happening here. I'm almost 100% positive it has to do with the layers - the bulk edit modal is not properly respecting the layers the marker should be on when it's drawing markers, so it shows _all_ of them (even if they're on a different layer), and when you save out of that modal, it places _all_ of them on the main layer.

If the markers were desynched to the main layer somehow, then clicking the bulk edit modal will "bring them back".

**Comment by Moonbase59** [comment]
"Bring them back" in the bulk edit, yes, because there’s no differentiation between layers. But if they’re just saved, they’ll be gone again after closing/reopening..

Btw, something’s odd with the default markers in bulk edit now, seems the icon is smaller and not transparent anymore:

![Auswahl_047](https://user-images.githubusercontent.com/3706922/125631840-0e872dcf-df3e-43da-afb4-110c73c5ea82.png)

Plus, the "Choose file" and "Upload file" now use the system language (de), not the language Obsidian is set to (en):

![Auswahl_048](https://user-images.githubusercontent.com/3706922/125632285-126e7dda-456c-46e9-9e77-7aa730c31ae9.png)

This is just a minor issue, though.

**Comment by valentine195** [comment]
oh whoops, I actually noticed that and fixed it but didn't release the update

Will be fixed in the next release

**Comment by Moonbase59** [comment]
Looks like Chromium would use the `gtk_file_chooser` in my case, and it has no separate language setting (picks up current system locale), so probably not worth the effort.

**Comment by Moonbase59** [comment]
> but they're tied to image name (couldn't think of a better way unfortunately) - could be because people renamed their image.

Yep, since we can have "named layers" now, this is surely the best way (generating fancy UUIDs and keeping them linked to something that could change seems overkill, I think).

**Comment by valentine195** [comment]
I think I'll implement two fixes:

1. Fix the bulk edit - only show markers on current layer
2. Display a list of "unassociated markers" - possibly a new control, with option to "add to main layer"?

**Comment by Moonbase59** [comment]
> they shouldn't be shown at all, so "bringing them back" is a bug that I'll fix

Yep, "bringing them back" to some "main layer" is a good idea. I only wonder about people using layered image maps (imagine the Colossal Cave) and have many markers on different layers. Introducing a "layer select" in bulk edit (_if_ there is more than one) would surely be too much, right?

**Comment by valentine195** [comment]
We'll see, I've been thinking I need to fix up the UI on that modal anyway.

By the way, a user on discord reached out, and I do know what caused this - the change to the YAML parsing :) the YAML parsing used to give me only the link, now I get the double brackets, which get URI encoded, which do not match the image names...

**Comment by Moonbase59** [comment]
> I think I'll implement two fixes:
> 
>     1. Fix the bulk edit - only show markers on current layer
> 
>     2. Display a list of "unassociated markers" - possibly a new control, with option to "add to main layer"?

Thinking about it, _not_ introducing another level of complicatedness might be good—so why not _sort_ markers by layer in bulk edit, _show all_, and have a "layer select" dropdown per marker? (Which could default to the current layer if none was set or it was "lost" due to renaming?)

**Comment by valentine195** [comment]
> Thinking about it, not introducing another level of complicatedness might be good—so why not sort markers by layer in bulk edit, show all, and have a "layer select" dropdown per marker? (Which could default to the current layer if none was set or it was "lost" due to renaming?)

The only reason I didn't want to do that was because loading the images is rather intensive (and slow), and the bulk map unfortunately has to re-load them. Switching layers for the first time to a large image can be _very slow_

**Comment by valentine195** [comment]
yep that's what I'm thinking

**Comment by valentine195** [comment]
Can you please see if the original issue still occurs in 3.19.7?

This release does not include fixes to the bulk edit modal.

**Comment by Moonbase59** [comment]
Original issue fixed :-) More to test?

**Comment by valentine195** [comment]
Nothing at the moment - will probably take a little break from the plugin. Thanks again for your help and enjoy your time!

**Comment by Moonbase59** [comment]
No, wait …

The two "vanished" markers reappeared but on initial view, a location gotten from

```yaml
markerTag: middleearth 
```

isn’t shown. This is shown if I close/reopen the note.

**Comment by Moonbase59** [comment]
Hm. After closing/restarting Obsidian a few times, it now works. Was I too fast? (Dataview indexer?)

**Comment by valentine195** [comment]
Hmm, bizarre - `markerTag` is working for me...

Yeah, that's possible. I'd like to break the dataview dependency but I really don't want to recreate the tag indexer. I wish Obsidian would add a full tag list into their API.

**Comment by Moonbase59** [comment]
Yep, that’d be good. They have a means to get all tags, and it’s probably much cleaner than the Dataview workaround.

**Comment by valentine195** [comment]
I believe this is fixed?

**Comment by Moonbase59** [comment]
Yep, seems I missed this. Closing ;-)
