### ISSUE TITLE
Mobile?

### ISSUE THREAD

**Issue by mhofherr** [valentine195/obsidian-leaflet-plugin#157]
Same as dice roller, would like to try this plugin on mobile app. Could you enable mobile for testing?

Thanks,
Matthias

**Comment by valentine195** [comment]
Hi, this one is going to take some extensive testing. I don't think it would even work on mobile as is, unfortunately, and the UX will need to be updated to support touch events.

**Comment by mhofherr** [comment]
Ok, understood. I will just use a normal include of my maps instead of Obsidian Leaf for now.

Thanks,
Matthias

**Comment by valentine195** [comment]
@mhofherr mobile support was added in 3.20.0

**Comment by mhofherr** [comment]
Tested it and worked without problems. Thanks a lot!
