### ISSUE TITLE
3.19.5: Lots of tiles all over the page

### ISSUE THREAD

**Issue by Moonbase59** [valentine195/obsidian-leaflet-plugin#161]
Upgraded from 3.19.1 to 3.19.5. Now all maps show lots of tiles placed all over the page …

![Knowledgebase - Obsidian v0 12 10_043](https://user-images.githubusercontent.com/3706922/125617224-ec3a6d68-ba33-462c-9715-690c051f4588.png)

Zoomed out:

![Knowledgebase - Obsidian v0 12 10_044](https://user-images.githubusercontent.com/3706922/125617342-bf90cb29-d209-4126-a657-c0aa8b87187c.png)

And here the Middle Earth Map as an example for image maps (zoomed out so artefacts can be seen):

![Knowledgebase - Obsidian v0 12 10_001](https://user-images.githubusercontent.com/3706922/125618178-ae681f3f-f55d-49d8-92f4-f947952b882a.png)

**Comment by valentine195** [comment]
Hmm... I didn't experience this on my testing maps :(

No errors in the console?

**Comment by Moonbase59** [comment]
Not one. If it helps, it seems my Obsidian has auto-upgraded from 0.12.5 to 0.12.10 in the meantime (but I restarted it again, to be sure).

Any time for checking? Just ’cause my daughter and family are dropping in tomorrow for a few days, and we were planning to do some excursions with the li’l one …

**Comment by valentine195** [comment]
Yeah, trying to think what could have caused this. I can always revert - this updates were just to avoid collisions with a new plugin that also uses Leaflet and was overwriting my Leaflet instance. My guess is there's something about the way Linux Chromium works that's different in this instance.

**Comment by valentine195** [comment]
Having said that, I _believe_ this is an issue of missing the LeafletJS CSS file (somehow). If you inspect the map element and view the styles applied to it, does it have the `leaflet.css` styles applied?

**Comment by Moonbase59** [comment]
Hmm. Here’s `navigator`:

```text
Navigator {vendorSub: "", productSub: "20030107", vendor: "Google Inc.", maxTouchPoints: 0, userActivation: UserActivation, …}
appCodeName: "Mozilla"
appName: "Netscape"
appVersion: "5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/0.12.4 Chrome/89.0.4389.128 Electron/12.0.6 Safari/537.36"
clipboard: Clipboard {}
connection: NetworkInformation {onchange: null, effectiveType: "4g", rtt: 0, downlink: 9, saveData: false}
cookieEnabled: true
credentials: CredentialsContainer {}
deviceMemory: 8
doNotTrack: null
geolocation: Geolocation {}
hardwareConcurrency: 4
hid: HID {onconnect: null, ondisconnect: null}
keyboard: Keyboard {}
language: "de"
languages: ["de"]
locks: LockManager {}
maxTouchPoints: 0
mediaCapabilities: MediaCapabilities {}
mediaDevices: MediaDevices {ondevicechange: null}
mediaSession: MediaSession {metadata: null, playbackState: "none"}
mimeTypes: MimeTypeArray {0: MimeType, 1: MimeType, application/pdf: MimeType, application/x-google-chrome-pdf: MimeType, length: 2}
onLine: true
permissions: Permissions {}
platform: "Linux x86_64"
plugins: PluginArray {0: Plugin, 1: Plugin, Chromium PDF Viewer: Plugin, length: 2}
presentation: Presentation {defaultRequest: null, receiver: null}
product: "Gecko"
productSub: "20030107"
scheduling: Scheduling {}
serial: Serial {onconnect: null, ondisconnect: null}
serviceWorker: ServiceWorkerContainer {controller: null, ready: Promise, oncontrollerchange: null, onmessage: null, onmessageerror: null}
storage: StorageManager {}
usb: USB {onconnect: null, ondisconnect: null}
userActivation: UserActivation {hasBeenActive: true, isActive: true}
userAgent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/0.12.4 Chrome/89.0.4389.128 Electron/12.0.6 Safari/537.36"
vendor: "Google Inc."
vendorSub: ""
wakeLock: WakeLock {}
webdriver: false
webkitPersistentStorage: DeprecatedStorageQuota {}
webkitTemporaryStorage: DeprecatedStorageQuota {}
xr: XRSystem {ondevicechange: null}
__proto__: Navigator
```

As you can see, my "Installer version" is 0.12.4, think it might make sense to upgrade the AppImage to 0.12.10, just in case?

**Comment by valentine195** [comment]
Worth a try...

**Comment by Moonbase59** [comment]
Ok, gimme a sec …

**Comment by Moonbase59** [comment]
Nope, exactly the same, even though they have upgraded to Electron 12.0.14. Chrome used is still 89.0.4389.128:

```text
Navigator {vendorSub: "", productSub: "20030107", vendor: "Google Inc.", maxTouchPoints: 0, userActivation: UserActivation, …}
appCodeName: "Mozilla"
appName: "Netscape"
appVersion: "5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/0.12.10 Chrome/89.0.4389.128 Electron/12.0.14 Safari/537.36"
clipboard: Clipboard {}
connection: NetworkInformation {onchange: null, effectiveType: "4g", rtt: 0, downlink: 10, saveData: false}
cookieEnabled: true
credentials: CredentialsContainer {}
deviceMemory: 8
doNotTrack: null
geolocation: Geolocation {}
hardwareConcurrency: 4
hid: HID {onconnect: null, ondisconnect: null}
keyboard: Keyboard {}
language: "de"
languages: ["de"]
locks: LockManager {}
maxTouchPoints: 0
mediaCapabilities: MediaCapabilities {}
mediaDevices: MediaDevices {ondevicechange: null}
mediaSession: MediaSession {metadata: null, playbackState: "none"}
mimeTypes: MimeTypeArray {0: MimeType, 1: MimeType, application/pdf: MimeType, application/x-google-chrome-pdf: MimeType, length: 2}
onLine: true
permissions: Permissions {}
platform: "Linux x86_64"
plugins: PluginArray {0: Plugin, 1: Plugin, Chromium PDF Viewer: Plugin, length: 2}
presentation: Presentation {defaultRequest: null, receiver: null}
product: "Gecko"
productSub: "20030107"
scheduling: Scheduling {}
serial: Serial {onconnect: null, ondisconnect: null}
serviceWorker: ServiceWorkerContainer {controller: null, ready: Promise, oncontrollerchange: null, onmessage: null, onmessageerror: null}
storage: StorageManager {}
usb: USB {onconnect: null, ondisconnect: null}
userActivation: UserActivation {hasBeenActive: true, isActive: true}
userAgent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/0.12.10 Chrome/89.0.4389.128 Electron/12.0.14 Safari/537.36"
vendor: "Google Inc."
vendorSub: ""
wakeLock: WakeLock {}
webdriver: false
webkitPersistentStorage: DeprecatedStorageQuota {}
webkitTemporaryStorage: DeprecatedStorageQuota {}
xr: XRSystem {ondevicechange: null}
__proto__: Navigator
```

**Comment by Moonbase59** [comment]
> Having said that, I _believe_ this is an issue of missing the LeafletJS CSS file (somehow). If you inspect the map element and view the styles applied to it, does it have the `leaflet.css` styles applied?

How can I be sure? Woulkd it display this as "leaflet.css" on the right? I inspected the `div.leflet-container`, `div.leafleat-pane.leaflet-map-pane` and `div.leaflet-pane.leaflet-tile.pane` but these all only show CSS from `app.css`, `user agent stylesheet` and `<style>`.

**Comment by valentine195** [comment]
Correct, it should show this:

![image](https://user-images.githubusercontent.com/38669521/125625278-4eec80b8-9d7b-4eee-b7cb-5e1bb2eb748a.png)

**Comment by valentine195** [comment]
Can you try 3.19.6?

**Comment by Moonbase59** [comment]
Yay :+1: you fixed it! And lots of `.leaflet` classes now turning up. Looks like you’re already working on my Android version to test soon? (Phew! Mobile!)

**Comment by valentine195** [comment]
Thank goodness! So bizarre, but I switched bundlers to make it easier to deal with this collision issue and webpack was putting the leaflet module's css into the JavaScript itself - I guess the Linux Chromium doesn't like that, because all I did was make it actually put it in the css file

**Comment by Moonbase59** [comment]
Interesting. I already wondered why you use the `mini-css-extract-plugin` now ;-)
The change won’t break Windoze and MacOS versions, right?

**Comment by valentine195** [comment]
Well, it doesn't break my windows dev machine, and 3.19.5 didn't break my personal Mac.

**Comment by Moonbase59** [comment]
Purr-fect! Thanks a bundle for this quick fix, now we can stroll through the woods together … :grinning: 

![Auswahl_045](https://user-images.githubusercontent.com/3706922/125628515-84d34a9e-1f02-455e-9913-168c38f653cd.png)

![Auswahl_046](https://user-images.githubusercontent.com/3706922/125629102-2f8f096f-c606-474d-9256-d11cc971563a.png)
<small>Photo credits: © 2019, Bodo Gewinner</small>

I’ll probably not be too responsive until about July 20, but after that I’ll happily discuss & test again!

**Comment by valentine195** [comment]
Enjoy!

**Comment by Moonbase59** [comment]
We’ll certainly do, thanks! Haven’t seen my daughter and my grandson for some time, so I’m really happy they drop in for a few days!

**Comment by valentine195** [comment]
> Looks like you’re already working on my Android version to test soon? (Phew! Mobile!)

Mobile should now work 😁
