### ISSUE TITLE
3.19.7 Copy coordinates not working

### ISSUE THREAD

**Issue by thefullmlg** [valentine195/obsidian-leaflet-plugin#163]
Have tried every combination of Shift-click, Control-Shift-click, Control-Alt-click, etc. Nothing is copied to clipboard. Have tried with setting on and off. Thanks.

**Comment by valentine195** [comment]
It is <kbd>Ctrl</kbd>-<kbd>Shift / Alt</kbd> click, I will update the setting to reflect this. However, I just tested and it works on my machine.

1. Can you tell me your operating system, please.
2. Do you get a Notice in the top left that the coordinates were copied?
3. If you open the console, are there any errors?

**Comment by Moonbase59** [comment]
<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+Click works for me (on Obsidian 0.12.10/Installer 0.12.10, Linux).

**Comment by thefullmlg** [comment]
Mac 11.4, Obsidian 0.12.10/Installer 0.8.0
No Notice that coords were copied.
No errors in the console.

Ctrl+Shift+Click gives me the circle overlay
Ctrl+Alt+Click gives me the marker pop up menu, like a right click.
Shift+Click displays the coordinates, but does not copy.

**Comment by valentine195** [comment]
Thanks, I think I know the issue - saw it in another key modifier. I need to look at the Meta key to capture the events properly on Mac. Will be fixed in the next release.

**Comment by thefullmlg** [comment]
Thanks. Just getting started with this plugin and love it. The markerTag/Dataview combo is amazing.

**Comment by valentine195** [comment]
Glad you like it!

**Comment by Moonbase59** [comment]
@thefullmlg: You might want to consider updating your installer one of the days, it’s quite old.

Reason: They upgraded Electron a few times since, and Electron updates can only be had by using a newer version of the installer.

And yes, it’s awesome what you can do with the Obsidian Leaflet! :-) Have fun with it.
