### ISSUE TITLE
Setting to permanently display marker tooltip

### ISSUE THREAD

**Issue by valentine195** [valentine195/obsidian-leaflet-plugin#177]
Possibly global + per-marker?

From a user on the Discord.

**Comment by Moonbase59** [comment]
Hm. On a map like below, it would fill the screen with tooltips (which already sometimes come in the way).

![Auswahl_164](https://user-images.githubusercontent.com/3706922/128038920-9e84ca35-b106-4ccd-b7ee-d954522d73ce.png)

But I can see uses (show home or current location, show tavern to reach in this game’s round). Maybe as an extra marker attribute plus a switch button on the map?

**Comment by Moonbase59** [comment]
Tooltip display on Hover/Never isn’t like "Always", or did I misunderstand what the user wanted?

**Comment by valentine195** [comment]
you didn't, I accidentally closed this one
