### ISSUE TITLE
Add grid option to image maps

### ISSUE THREAD

**Issue by valentine195** [valentine195/obsidian-leaflet-plugin#178]
http://turfjs.org/docs/#hexGrid

**Comment by Moonbase59** [comment]
Nosy me: What would be a use case?

**Comment by valentine195** [comment]
Lots of TTRPGs are done on hex grids (this is where the term "hex crawl" comes from)

**Comment by Moonbase59** [comment]
Which? The GPX? :grin:

**Comment by valentine195** [comment]
Both? :)

**Comment by valentine195** [comment]
Not feasible. Closing.
