### ISSUE TITLE
3.21.3: Usability: Can’t add mutable marker where an overlay shows

### ISSUE THREAD

**Issue by Moonbase59** [valentine195/obsidian-leaflet-plugin#184]
Just realized (I use mutable markers only on fantay (image) maps) that a new marker cannot be added wherever an overlay shows: "This overlay cannot be edited because it was defined in the code block."

Have to switch off (filter) all entries that might generate overlays, _then_ it works.

This might turn out not easy, since the layer arrangement and z-axes have been rather fine-tuned over time ;-) Might be a real use case for #179 (I could live with that).

**Comment by valentine195** [comment]
I could just propagate the click event on an immutable overlay. _Probably_ not possible on a mutable one, though, unless I add an option to the context menu to "edit overlay"

**Comment by Moonbase59** [comment]
That possible? Sounds a neat way. But what if you had several overlays on top of each other (like my home "nearby" plus the "current location" plus the "Krumbach town" overlays)?

**Comment by valentine195** [comment]
not too difficult to grab each layer that the event can propagate through and display a context menu that has all 3 + "add marker"

I actually like this quite a bit, feels like a big step up in usability

**Comment by Moonbase59** [comment]
Probably a rather dumb quetion, haven’t been sitting on a Mac for years: Do Macs nowadays _have_ more than one mouse button?

**Comment by valentine195** [comment]
Macbooks do not but two-finger clicks are right-clicks.

Not sure about the desktops, but you can always use whatever mouse you want there 🤷🏼

**Comment by Moonbase59** [comment]
Not that we make things unusable by having right-clicks where no one can use them, hee hee … Good to know, so Mac users go buy a two- or three-button mouse! :rofl:

**Comment by valentine195** [comment]
Yeah...that update isn't going to be easy.

**Comment by valentine195** [comment]
Please try this in 3.22.0.

Also, let me know how you like the behavior of the context menu when right-clicking on multiple overlapping mutable overlays.

**Comment by Moonbase59** [comment]
I would, but only after creating a mutable overlay, right-clicking to edit it, and closing the edit modal … it’s vanished. (Somehow reminds me of an old bug?)

**Comment by valentine195** [comment]
Thanks, I'll look into that.

> Auto-moving the map to the overlays needs getting used to (especially if one only wanted to add a marker and accidentally hovers over the Overlays).

This is the behavior I meant above - wasn't sure about how it felt.

**Comment by valentine195** [comment]
> I would, but only after creating a mutable overlay, right-clicking to edit it, and closing the edit modal … it’s vanished. (Somehow reminds me of an old bug?)

I actually can't recreate this behavior. That's bizarre.
