### ISSUE TITLE
3.23.2: "always" tooltip stays on map after deleting mutable marker

### ISSUE THREAD

**Issue by Moonbase59** [valentine195/obsidian-leaflet-plugin#193]
I was just experimenting with a marker having an "always" shown tooltip. Works ok _but_ when erasing that marker from the map using the edit modal, the tooltip stays on the map. (Until you close/reopen it.)

**Comment by valentine195** [comment]
I did notice that, actually. Thanks for the reminder.

**Comment by valentine195** [comment]
Fixed in 3.23.3

**Comment by Moonbase59** [comment]
Confirm fixed.
