### ISSUE TITLE
3.24.0: Old bug again: Overlays (from notes) not removed when filtering marker

### ISSUE THREAD

**Issue by Moonbase59** [valentine195/obsidian-leaflet-plugin#195]
Using "nearby" overlays in notes. These should vanish (together with the marker) if the marker gets "unfiltered".

![Auswahl_097](https://user-images.githubusercontent.com/3706922/128400675-20551e71-ea1f-4b1b-80ab-cc11b3aab475.png)

![Auswahl_098](https://user-images.githubusercontent.com/3706922/128400685-efea6560-58c1-4efd-8459-010303b1b7df.png)

**Comment by valentine195** [comment]
Not sure how this came back, but should be fixed.

**Comment by Moonbase59** [comment]
Nope, unfortunately not (using 4.0.0 since 3.24.3 can’t install).

**Comment by Moonbase59** [comment]
Confirm working in 3.24.3 though.
