### ISSUE TITLE
FR: Make it easier to annotate map w/o linking or allow linking to nonexistent note

### ISSUE THREAD

**Issue by brimwats** [valentine195/obsidian-leaflet-plugin#201]
I am using leaflet to keep track of recommendations and places I want to see, like this:

![image](https://user-images.githubusercontent.com/49103046/128715769-9c0338e9-998d-4d97-98c2-4c0092b571a6.png)

When I add a marker I actually just want to add text to the hover tooltip without making or linking it to a note. As there's no place to put that, I have to put it in "Note to open" — which is fine, maybe i'll want to make a note about it later on. But when i hit tab here it will just add in the autosuggested item:

![image](https://user-images.githubusercontent.com/49103046/128716064-3e0b31de-2ee1-442c-9bba-32b17498f1bf.png)

This leads to a lot of frustrating clicking around the box until it accepts a nonexistent note.

**Comment by valentine195** [comment]
You can close that box by hitting <kbd>Escape</kbd> and it will accept whatever you put in
