### ISSUE TITLE
[Feature] Array of locations

### ISSUE THREAD

**Issue by kometenstaub** [valentine195/obsidian-leaflet-plugin#204]
I would like to associate multiple locations with people.

This would be possible with an array of locations.

Current workaround: [Mapmarkers](https://github.com/valentine195/obsidian-leaflet-plugin#mapmarkers)

**Comment by Moonbase59** [comment]
Haven’t used it for a while, but we have YAML marker for use in notes:

```yaml
marker:
    - [<type>, <lat>, <long>, <link>]
    - [<type>, <lat>, <long>, <link>]
```
