### ISSUE TITLE
Latency when revising gpx tracks

### ISSUE THREAD

**Issue by erex** [valentine195/obsidian-leaflet-plugin#208]
Creating a map of hillwalks from a number of existing gpx files.  A couple gpx file contain errors, as can be seen here:

![image](https://user-images.githubusercontent.com/330744/129870076-7c8d2c5f-cf37-40aa-be33-1dc25a3f554b.png)

I edit the offending gpx files to correct the errors, but the leaflet map still shows the errors.  Is there some sort of refresh that will cause the gpx file to be re-read?

I conducted an extreme experiment, where I created an Obsidian file with a single gpx track, referencing a gpx file in my vault.
![image](https://user-images.githubusercontent.com/330744/129870619-7813f7c6-8d82-4740-8588-ecdd8d13856e.png)

I then moved the file out of my vault to my Windows desktop, expecting the preview to fail because there was no longer a gpx file.  To my surprise, the preview rendered just as it did before.  That lead me to wonder about latency and refreshing.

**Comment by valentine195** [comment]
Did you close and re-open the note with the map? The plugin reads the data every time it builds the map, which is when the note is opened or a change has been made to the code block in edit mode.

**Comment by erex** [comment]
Yes, note closed and reopened.  mp4 below of the sequence, with Obsidian and subfolder of the vault shown.

https://user-images.githubusercontent.com/330744/129887158-477f5481-088d-4e04-871f-cd15fb3161af.mp4

The gpx file in question does not exist in the vault (having been moved previously), but it did at one time exist in the vault.  Hence the appearance of memory on the part of leaflet.

My vault exists in a "Dropbox-like" cloud storage, called Nextcloud.  It seems unlikely that Nextcloud is the cause of this, otherwise edits to plain text Obsidian notes would not be reflected in preview.

**Comment by valentine195** [comment]
Hmm, interesting. I suppose it is _possible_ that Obsidian has cached this data... does it still happen if you close and re-open Obsidian?

I do not do anything special when loading GPX/GeoJSON - I just use Obsidian's built in file reading API.

**Comment by erex** [comment]
Yes, same issue when opening/closing Obsidian.  I started building these trail maps on Sunday (15Aug), discovered the problem of not recognising edits and set the problem aside.  Saw a new release of Leaflet plug-in this morning and installed the update and returned to the subject.  Between Sunday and today, I had opened and closed Obsidian more than a few times. Decided I would raise as an issue.

**Comment by valentine195** [comment]
Are you _sure_ that there isn't a file named that somewhere in your vault?

If it loads a file even when restarting Obsidian, then Obsidian is finding that file somewhere in its file tree.

**Comment by erex** [comment]
Thanks for your persistence Jeremy.  There were duplicate .gpx files in my vault.  I was carrying out edits to the .gpx files in the same folder as the note, but lurking in the root of my vault were the same .gpx files (that remained unedited).  Thanks for your work on the plug-in and your patience with my self-induced error.

**Comment by valentine195** [comment]
Glad we could figure it out! I use Obsidian's API for opening a file name, which will open the first file matching that name closest to a given folder. Currently I just use the root for this, but in the next major release it will be changing to the location of the note containing the map - that will probably help with the map opening unexpected files.
