### ISSUE TITLE
[Bug] `mapmarkers` doesn't work without `location`

### ISSUE THREAD

**Issue by kometenstaub** [valentine195/obsidian-leaflet-plugin#211]
> The `mapmarkers` parameter can be used to define an arbitrary number of markers to display on the map. This does not require the `location` tag to be set.

If I don't set a location in a note in YAML frontmatter, it won't show the `mapmarkers` I have set up for that note.
I have set the correct `markerFolder` in the map code block. As soon as I add the `location` and reload the app, both the `location` and the `mapmarkers` for that note appear in the map.

**Comment by valentine195** [comment]
Fixed in 3.24.14
