### ISSUE TITLE
Using alternative layers (rather than Openstreetmap)

### ISSUE THREAD

**Issue by erex** [valentine195/obsidian-leaflet-plugin#216]
## More a question than an issue

Really enjoying the plugin for documenting and planning hillwalks with GPX files.  Would like to have an alternative base map showing topographic contours, such as OpenTopoMap.  Unfortunately, I can't understand the image specification syntax to make it work with the plugin.

Using the [demo](http://leaflet-extras.github.io/leaflet-providers/preview/index.html) page to preview various layers, I find
![image](https://user-images.githubusercontent.com/330744/130580426-37511f45-9d63-412c-9015-0c260f176be3.png)

How do I translate this into syntax for use with `image: `

**Comment by valentine195** [comment]
So this is an additional `TileLayer`. Adding this would replace the OpenStreetMap view. 

I actually would like to support additional tile layers, it would just be on the user to ensure they’re usable.

**Comment by erex** [comment]
Thanks Jeremy.  Just to be clear, the user (me) cannot yet specify an alternative base map, need to await this feature in the plugin, correct?

**Comment by valentine195** [comment]
Correct

**Comment by erex** [comment]
Thanks again, awaiting future developments 🚶‍♂️

**Comment by valentine195** [comment]
Hi, this feature will be in the next major release (next week or so, hopefully).

**Comment by valentine195** [comment]
Closed with 4.0.0 release.
