### ISSUE TITLE
Export to html

### ISSUE THREAD

**Issue by erex** [valentine195/obsidian-leaflet-plugin#221]
Continue to enjoy the plugin.  I would like to be able to share maps produced by the application with colleagues, outside of Obsidian.  Want to produce an html file with the interactivity of the map.  Pandoc conversion from .md to .html only produces the raw codeblock rather than the rendered version.

**Comment by valentine195** [comment]
Yeah, this would be quite difficult, and you would need to load several NPM modules into your HTML content to view the map.

I'll think about if its possible, but at the moment I'm going to close this for being out-of-scope.

**Comment by erex** [comment]
That's fine, thanks for considering it.
