### ISSUE TITLE
Add option to style map markers based on (eg) tags

### ISSUE THREAD

**Issue by HEmile** [valentine195/obsidian-leaflet-plugin#222]
In Obsidian Map View (https://github.com/esm7/obsidian-map-view), you are able to style the map markers based on tags in the note the frontmatter is in. While in Obsidian leaflet, you are able to style based on frontmatter, this would mean having to copy this style information to every note with that same tag. 

The feature request is to add some way to conditionally style the map markers based on (for example, in this use case) tags in the note. My personal preference would be to have this in the plugin options, so I won't need to copy this style information to every leaflet code block.

**Comment by valentine195** [comment]
This will be released in 4.0.0.

**Comment by HEmile** [comment]
That was quick! Thank you so much. Looking forward to the release :)
