### ISSUE TITLE
Save markers to YAML

### ISSUE THREAD

**Issue by tuxtlequino** [valentine195/obsidian-leaflet-plugin#228]
Have the option to save markers and overlays into the YAML description. Maybe adding a little button that copies that info into YAML will be the way the way to go. I understand that leaflet uses JSON to create and modify those markers, but having the option to copy that info without looking into the JSON file would be amazing.

For my case, this is the best plugin I have found. Awesome work!

**Comment by valentine195** [comment]
Should be easy enough. You'd want it to go into the map code block and not a note's frontmatter, correct?

**Comment by tuxtlequino** [comment]
Yes. Doing that would be awesome.

**Comment by valentine195** [comment]
Added this ability to the right click context menu in 4.1.0
