### ISSUE TITLE
It would be nice if the file names were displayed

### ISSUE THREAD

**Issue by zhl111** [valentine195/obsidian-leaflet-plugin#231]
![image](https://user-images.githubusercontent.com/29135984/134805073-88f58cf1-4433-458f-9315-f92a51fe428e.png)

**Comment by HEmile** [comment]
I was just about to make a feature request for this! It can indeed be hard to figure out the file name of a marker.

**Comment by valentine195** [comment]
Filenames will display even if note previews are on as of 4.1.0
