### ISSUE TITLE
Is it possible to toggle Geojson layers?

### ISSUE THREAD

**Issue by ForTehLose** [valentine195/obsidian-leaflet-plugin#241]
I have a map in Geojson cells, and rivers is another Geojson file. Is there a way to add them as two layers and have the ability to toggle then individually?

**Comment by valentine195** [comment]
They should actually already be added as individual layers. Should be pretty easy to add them to the layer or filter toggle. Probably layer?

**Comment by ForTehLose** [comment]
Trying to make the Geojson results in it not loading
Or at least the following didn't work
geojson: [[Elkia Cells 2021-10-03-02-27.geojson | cell]]

**Comment by valentine195** [comment]
You can’t put aliases on the GeoJSON links

**Comment by ForTehLose** [comment]
Ah I see, when adding Geojson to a map with multiple images layers is looks like they are added to the first layer, is there a way to specify which they get added to?

**Comment by valentine195** [comment]
Not at the moment. Should be possible to do though once I have some time
