### ISSUE TITLE
All the markings of the previous document have disappeared. I don't know what went wrong

### ISSUE THREAD

**Issue by zhl111** [valentine195/obsidian-leaflet-plugin#244]
The reason for the plugin upgrade?
![image](https://user-images.githubusercontent.com/29135984/136959569-e41b33f1-cff9-4fb4-abcc-b7e1e8976cc7.png)

**Comment by claremacrae** [comment]
Thank you. Over to you, @valentine195

**Comment by zhl111** [comment]
Hi，Thank you very much for your help, I found the historical version of the file. But when I overwrite the JSON file in (obsidian-leaflet-plugin), the marker icon doesn't show up. After restarting obsidian the JSON is overwritten, can you please tell me what to do? Thank you very much!
[data.zip](https://github.com/valentine195/obsidian-leaflet-plugin/files/7350195/data.zip)

**Comment by zhl111** [comment]
Repeated many times, JSON is automatically overwritten and becomes 4kb in size
![image](https://user-images.githubusercontent.com/29135984/137446772-e94f7bb2-cbb5-447b-914b-4b744d7db3db.png)

**Comment by valentine195** [comment]
Great, sorry about that. Glad we could recover the data :)
