### ISSUE TITLE
markerFolder with path containing emojis

### ISSUE THREAD

**Issue by galsom** [valentine195/obsidian-leaflet-plugin#245]
First of all I’d like to thank you for this great plugin! 👍 

I’m trying to make use of the markerFolder option for a path that contains emojis, like e.g.

`markerFolder: "08. 🗄️ Reference System/08. 🧭 Places"`

This however seems to return no markers (at least locally on macOS Big Sur). 

<img width="884" alt="image" src="https://user-images.githubusercontent.com/48659253/137317091-e2524d4e-e66e-4ff3-b67c-82649e1bcf48.png">

When I rename the folders to not include any emoji, then the markers do appear:

`markerFolder: "08. Reference System/08. Places"`

<img width="885" alt="image" src="https://user-images.githubusercontent.com/48659253/137317797-d6df3701-5539-4694-90bc-dad41f84d475.png">

It does seem to work on the iOS mobile app with the emojis in the path 👌.

![image](https://user-images.githubusercontent.com/48659253/137316934-7a4725cb-c5f1-4758-a595-8e8730fd18a1.png)

Would it be possible to support a path containing emojis?

**Comment by valentine195** [comment]
Sure, two things:

1. Are there any errors in the developer console when you open the map? (Cmd-alt-i on Mac). 
2. If not, if you type `app.vault.getAbstractFileByPath("08. 🗄️ Reference System/08. 🧭 Places")`, does it return an object or null?

**Comment by galsom** [comment]
For some reason, this started working again. Thank you for looking into it!
