### ISSUE TITLE
All locations in English

### ISSUE THREAD

**Issue by Archie-2021** [valentine195/obsidian-leaflet-plugin#247]
Is it possible to get all the names in Latin alphabet at least. In openstreetmap it's is possible in different layers to get such a result. Is it possible to get those layers in obsidian. If not consider this a feature request.

Thanks for this great plugin

**Comment by Archie-2021** [comment]
> Hi, you can specify alternate tile servers for the map, if you know one with the names you would want. 
> 
> https://github.com/valentine195/obsidian-leaflet-plugin#real-world-maps

Thanks. Is there a place to look for these tile servers?

I should add it in osmLayer field, right? Just to make sure

**Comment by valentine195** [comment]
You use the `tileServer` parameter. `osmLayer` is used to turn the “regular” layer off. 

[This](https://leaflet-extras.github.io/leaflet-providers/preview/) is a good source for tile servers, although I’m not sure all of them would work.
