### ISSUE TITLE
Resize map based on aspect ratio of supplied image

### ISSUE THREAD

**Issue by farling42** [valentine195/obsidian-leaflet-plugin#254]
I am using leaflet to display an image to the user, on which is placed one or more map pins.

With normal images in Obsidian the image is stretched in size keeping its aspect ratio when the window is resized.

With Leaflet, the width of the map view is resized, but the vertical height is not resized.

Perhaps just a simple "aspectRatio" flag would be enough that can be set to a specific value, so that when the width of the map view box changes then the height can be adjusted by the same ratio.

**Comment by valentine195** [comment]
This functionality was added in 4.4.0, using the new `preserveAspect` map block parameter.
