### ISSUE TITLE
Add heading and block references to marker

### ISSUE THREAD

**Issue by trungng2006** [valentine195/obsidian-leaflet-plugin#26]
Would it be possible to add `heading and block references popup preview for the marker` (rather than the whole note).
I think this would be a nice addition to the plugin.
Thank you!

**Comment by valentine195** [comment]
Is this something that Obsidian does elsewhere? Right now the plugin just tells Obsidian that the marker is an internal note link, so Obsidian is handling the rendering of the note preview window.

**Comment by trungng2006** [comment]
This is the current ability of Obsidian. 
For example: if I have a note name NOTE and heading HEADING 1, HEADING 2, HEADING 3
I will type: [[NOTE#HEADING1]] 
When hovering over the link, it will only show heading 1 of that note

**Comment by trungng2006** [comment]
![image](https://user-images.githubusercontent.com/71961905/113311679-24d21280-933c-11eb-8ae3-211fada4e484.png)
To help illustrate

**Comment by valentine195** [comment]
Oh, so actually _linking_ to the heading or block references. Sorry, I misunderstood - yes, that should be possible.

**Comment by trungng2006** [comment]
That sound wonderful! Thank you so much!

**Comment by trungng2006** [comment]
Thank you for implement this feature so quickly, but may I ask how to link with heading? 
because right now the base marker show "note to open" via path to note. I'm not sure how to link with heading.

**Comment by valentine195** [comment]
You can just append it at the end.

`Note#Heading`

I removed the requirement for a path, but if you have multiple notes with the same name it may not open the note you expect.

I'm working on a full overhaul of the marker target ui (#15), which would make setting the marker target equivalent to making an internal Obsidian link (with the autocomplete, etc).

**Comment by trungng2006** [comment]
Thank you so much!
