### ISSUE TITLE
Why is there a blank after the upgrade?

### ISSUE THREAD

**Issue by zhl111** [valentine195/obsidian-leaflet-plugin#260]
![image](https://user-images.githubusercontent.com/29135984/145665849-bbb93713-afbd-4397-ab7e-844c82407dfd.png)

**Comment by valentine195** [comment]
This should be fixed if you update now. Sorry about that.

**Comment by zhl111** [comment]
3.7.4....but It cannot be panned!

**Comment by valentine195** [comment]
Can you explain what you mean? I'm not seeing any issues on my end.

**Comment by zhl111** [comment]
Why does the rectangle I draw disappear?
![动画](https://user-images.githubusercontent.com/29135984/145680099-3f9b397e-5f68-45bd-a047-66af9f2a1e6d.gif)

**Comment by valentine195** [comment]
Okay thank you, I will take a look. Are there any errors in the developer console? (Open with ctrl-shift-i or cmd-alt-i on Mac)

**Comment by zhl111** [comment]
![image](https://user-images.githubusercontent.com/29135984/145697995-3f15196e-edc7-4c5c-a762-301d6a2f49fb.png)
