### ISSUE TITLE
Can I change the language of the map to my country's language? I can't read it when locating is a huge obstacle

### ISSUE THREAD

**Issue by zhl111** [valentine195/obsidian-leaflet-plugin#261]
![image](https://user-images.githubusercontent.com/29135984/145934354-2268bbcf-a886-48ba-a0ac-1b429b9a73c6.png)
like this:
![image](https://user-images.githubusercontent.com/29135984/145934932-c4c6a4bb-b802-4b4b-bd71-b88797d6dbc9.png)

**Comment by valentine195** [comment]
I get my map data from OpenStreetMaps. If you can find a map tile server in your language, you could load it using the `tileServer` option.

**Comment by zhl111** [comment]
ok,I found it. But how do I set it as the default layer? That way I don't have to switch every time

**Comment by zhl111** [comment]
My problem, the method of deletion is not mastered
