### ISSUE TITLE
Can't delete polyline once drawn

### ISSUE THREAD

**Issue by benbarbour** [valentine195/obsidian-leaflet-plugin#264]
Maybe I'm being dumb, but I can't seem to find a way to do this.

**Comment by zhl111** [comment]
This requires skill, you have to tap the delete button first, and then tap the created shape

**Comment by benbarbour** [comment]
Thanks. I was fiddling late and I think I kept trying to click the nodes (apparently with pinpoint accuracy!) to delete the line, instead of the line itself. :p

**Comment by valentine195** [comment]
I can maybe try to improve this but one issue is deciding which shape to delete if their are linked together. Theoretically it’ll delete the node on top which would’ve been the last shape to be linked, though, which I suppose would be desired behavior.
