### ISSUE TITLE
2.0.1 "There was an error loading the map" when leaving "Base map marker" field empty

### ISSUE THREAD

**Issue by Moonbase59** [valentine195/obsidian-leaflet-plugin#28]
According to previous docs, "Base map marker" should be left blank to get full-sized marker symbols.

If I empty this field (it had `map-marker` before), the map will not render but produce the error "There was an error loading the map".

**Comment by valentine195** [comment]
Fixed in 2.0.2.

The default marker now _must_ be defined, but there is a new Layer Base Marker setting that will stop layering the additional markers by default.
