### ISSUE TITLE
Pretty please support markdown links

### ISSUE THREAD

**Issue by ebullient** [valentine195/obsidian-leaflet-plugin#280]
I prefer using markdown links to wiki links, which means Obsidian converts all of my autocompleted links to markdown links, which means I can't use autocomplete and have to manually type links (whether block references or header references or just links to other notes generally.

```
id: waterdeep-map
...

marker: default,...,...,[[#The Skewered Dragon]],The Skewered Dragon,-2,2
marker: default,...,[[#The Yawning Portal]],The Yawning Portal,-2,2
```

Using auto-complete, the same would be: 

```
marker: default,...,...,[The Skewered Dragon](#The%20Skewered%20Dragon),The Skewered Dragon,-2,2
marker: default,...,...,[The Yawning Portal](#The%20Yawning%20Portal),The Yawning Portal,-2,2
```

Note these are header references (same doc)..

**Comment by MILKMILKKING** [comment]
+1, I want this too
