### ISSUE TITLE
Double-click on the pin to go directly to the Edit Marker and type in the Note to Open item

### ISSUE THREAD

**Issue by MILKMILKKING** [valentine195/obsidian-leaflet-plugin#285]
This is a great plugin! Can it be further optimized though?

Currently, I need to right-click on a pin before entering Edit Marker, and  need to mouse-over the Note to Open item to enter the added note name.It would be more efficient if I could double-click on a pin to edit a Note to Open item directly. (Currently double-clicking on a pin simply enlarges the image, which doesn't feel very useful).

Thanks for your hard work!

**Comment by valentine195** [comment]
This was actually done with 4.14.0, just forgot to close this :) https://github.com/valentine195/obsidian-leaflet-plugin/releases/tag/4.14.0
