### ISSUE TITLE
FR: Hover over markers to open Page Preview

### ISSUE THREAD

**Issue by HEmile** [valentine195/obsidian-leaflet-plugin#287]
With the new Obsidian Hover Editor plugin, the page preview when hovering over a link has become much more useful. This could be a very nice (and easy to implement!) feature for Leaflet! (NB: I also have this issue in the Map View repo, I think it makes sense in both plugins.)

For example, when holding cmd/ctrl down and hovering over a note for eg 200 ms, you can trigger the link-hover event like this:
this.plugin.app.workspace.trigger('link-hover', this.element, null, file.path, '')

**Comment by valentine195** [comment]
Sorry, forgot to respond to this. This has been implemented in the plugin from the beginning (see [here](https://github.com/valentine195/obsidian-leaflet-plugin/blob/ae1ca527cada0ed6cac4d1468a8aa2a5492961b2/src/layer/marker.ts#L366-L372). You do have to enable it in Leaflet settings though.
