### ISSUE TITLE
[GPX] Change tooltip speed measure to Metric (km/h)

### ISSUE THREAD

**Issue by MiracleXYZ** [valentine195/obsidian-leaflet-plugin#288]
I just imported a GPX file of my workout (from Apple Watch) and got the tooltip:

1. The tooltip is good, but is there an option to change the measure to Metric? (i.e. mph -> kmh) (I already set `unit` to `meters` but it doesn't work on the tooltip)
2. How can I "Zoom to 1 GPX Track" automatically? `showAllMarkers` doesn't work. Would love it if there is a `zoomToOneGPXTrack` option.

<img width="103" alt="image" src="https://user-images.githubusercontent.com/30370926/158432803-8769dfb6-753c-4de6-aaa2-c6e4f76ffd48.png">

Thanks!

**Comment by valentine195** [comment]
Can you make the second request its own issue?

I fixed the first request, that was actually a bug.

**Comment by valentine195** [comment]
Actually, your first request can be done - I just forgot to document it. Use the `zoomFeatures: true` parameter in your map.

**Comment by MiracleXYZ** [comment]
It works perfectly. Thanks!
