### ISSUE TITLE
Question: Markers in leaflet block?

### ISSUE THREAD

**Issue by steve-bate** [valentine195/obsidian-leaflet-plugin#29]
Thanks for this plugin. Do you have any plans to allow markers to be defined directly in the leaflet block?

**Comment by valentine195** [comment]
The issue with this feature is keeping the source text in sync when markers are added/removed/edited in preview mode.

I think this will be easier when Obsidian v0.12 is released as it will be easier to modify the source block with some of the new API, so once that releases I'll look into adding it as a feature.

**Comment by steve-bate** [comment]
Thanks for the quick response. In my case, I'd be fine without the synchronization. Another possibility is to have a configuration option to select either an "embedded marker mode" or "preview marker entry mode" (the current behavior). In the embedded marker mode, the preview marker entry would be disabled.

**Comment by valentine195** [comment]
Hmm, ok, I'll think about this some more. Not keeping it in sync causes its own problems. The map object isn't persistent - if you close a note, the map object is destroyed, then when you re-open it, it is built from cached data. If someone creates a marker in the block, then moves it, the map would have to know that it should not **re-create** that marker when it opens again.

**Comment by Moonbase59** [comment]
There’s still some thinking to be done in this respect. Just imagine you rename the note containing the map, or the folder(s) it’s in … all markers gone, everytime.

**Comment by valentine195** [comment]
I agree. I'm still trying to think of a better way to store references to maps. It's difficult, because Obsidian doesn't expose a way to get a block reference id unless it has already been defined, from what I can tell. 

An quick and dirty solution is to just give each map a GUID that gets written and saved into the markdown (if a custom id is not provided). I toyed around with this solution but ended up not liking modifying source files, so I scrapped it. In hindsight I think this would be the best solution.

**Comment by steve-bate** [comment]
>  If someone creates a marker in the block, then moves it, the map would have to know that it should not **re-create** that marker when it opens again.

Yes, I was thinking the block-based markers would be immutable in the preview, but maybe that's not possible.

**Comment by Moonbase59** [comment]
> I was thinking the block-based markers would be immutable in the preview, but maybe that's not possible.

That’s actually a nice idea. So users can’t move around "predefined, fixed" markers all over the Earth!

**Comment by valentine195** [comment]
Yes, immutable markers are possible. I will work on it and add this feature.

Another idea I just had would be to add a `markerFile` parameter, where you could point the map towards a CSV/note list of defined markers. Again, these would (most likely) need to be immutable.

**Comment by Moonbase59** [comment]
> point the map towards a CSV/note list of defined markers

As long as this file is accessible (i.e., not buried within hidden `.obsidian` structures, that would be really elegant. Why? Because location data could be created a) from other notes, b) from some external tool or database.

**Comment by valentine195** [comment]
Yes, the intention there would be the user would input a path into the leaflet code block.

**Comment by Moonbase59** [comment]
Would it have to be a path? Or could it be put, say, in the "attachments" folder and linked via Obsidian’s wikilinks?

**Comment by valentine195** [comment]
Possibly. Obsidian just sends the raw text to the post processor, so I would just get [[Filename]], but I _think_ that would be enough information to find the file using the exposed API.

**Comment by Moonbase59** [comment]
Thinking further … links …
- it should eventually be possible to use _both_ internal & external links in the "places file" (or CSV). Reason: One might want a location entry with _no internal note_ but pointing to, say, an _external link_ like Wikipedia.

Thinking of a possible CSV structure (eliminating all internals):
```csv
Marker Type,Link,lat,lon,radius in m
Friends,"[[Moonbase59]]",48.23875,10.37595,OrangeCircle,50
Location,"https://de.wikipedia.org/wiki/Weltzeituhr_(Alexanderplatz)",52.52134162768218, 13.41327381161729,,
```
where the last two columns (if defined) could point to an overlay type defined elsewhere, and the desired radius.

Just thinking out loud … maybe attaching the overlay to an entry isn’t a good idea, after all.

**Comment by valentine195** [comment]
Added `marker: <type>,<lat>,<long>,<link>` parameter in 2.1.0 that creates immutable markers.

Link may be an Obsidian wikilink.

**Comment by valentine195** [comment]
Two new parameters added in 3.0.0:

`markerFile: [[Wikilink]]` / `markerFile: Direct/Path/To/Note`

and

`markerFolder: Direct/Path/To/Folder`

`markerFile` will read a note's frontmatter and create a marker based on these two tags:

`location: [lat, long]` **REQUIRED**
`marker: <marker-type-from-settings>` **OPTIONAL**

`markerFolder` will go through _all_ notes in a specified folder and read the frontmatter as above.
