### ISSUE TITLE
Custom geojsonColor is always black

### ISSUE THREAD

**Issue by arakis** [valentine195/obsidian-leaflet-plugin#292]
`geojsonColor` will always use "black" color, regardless of it's value.

```
id: possible-world-routes
lat: 30
long: 50
defaultZoom: 4
lock: true
geojson: Documents/world.geo.json
geojsonColor: #ff0000
```
will be rendered to:
![image](https://user-images.githubusercontent.com/1831942/160230930-e25fbeda-a06b-45e5-a153-3c9f752b6374.png)
Without the `geojsonColor` it looks like (thats correct): 
![image](https://user-images.githubusercontent.com/1831942/160230953-2addd8be-b97d-4eb9-aad1-13fbe82dd162.png)

**Comment by valentine195** [comment]
You need to put quotes around it. `#` starts a YAML comment, so you’re providing a null color (which is black).
