### ISSUE TITLE
Filterable Markers

### ISSUE THREAD

**Issue by valentine195** [valentine195/obsidian-leaflet-plugin#31]
- [x] Marker filters on Map UI
- [ ] Marker tagging
- [ ] Searchable markers

Would it have to be a path? Or could it be put, say, in the "attachments" folder and linked via Obsidian’s wikilinks? (Think: renaming/moving stuff)

Pros of this:
- Many maps could reuse the same data (say, "Friends & Family" file, "Business Contacts" file, "Interesting Locations" file).
- Maybe a CSV (map object location entry) could also contain tags? Then some _filtering_ from the same CSV data could be applied, like on _marker type_ or _tag(s)_. (i.e., show only friends, family members and interesting locations around a defined location, based on a CSV file that simply holds _all_ location types)

_Originally posted by @Moonbase59 in https://github.com/valentine195/obsidian-leaflet-plugin/issues/29#issuecomment-826968514_

**Comment by Moonbase59** [comment]
Currently, when filtering _out_ some markers,

- their position is still used by the "Show all markers" button. I feel that if we’re not showing them, they shouldn’t influence anything. And the "Show all markers" button probably be grayed-out (made unclickable) when "None" is selected in filtering.

- the overlay gotten from an `overlayTag` is correctly disabled.

- the overlay gotten from a `mapmarker` in a note that has it’s marker currently _not_ shown _is_ shown. I’d somehow feel that if a "marker" entry gotten from a note is not shown by filtering, also their associated `mapmarker` overlays should be hidden.

**Comment by valentine195** [comment]
> their position is still used by the "Show all markers" button. I feel that if we’re not showing them, they shouldn’t influence anything. 

Hmm...this used to be the case. If it's being influenced by unfiltered markers, I must have accidentally reverted that.

> And the "Show all markers" button probably be grayed-out (made unclickable) when "None" is selected in filtering.

Probably a good idea - I had it zooming fully out, probably unintended behavior.

I'll take a look at the overlay behavior - the filter is just looking at markers right now.
