### ISSUE TITLE
Rendering Map Markers based on metadata 

### ISSUE THREAD

**Issue by caglarongan** [valentine195/obsidian-leaflet-plugin#315]
Hello, many thanks for the amazing plugin ! 

Would you consider adding the ability to create (or associate) map markers based on a note's frontmatter ?
Because I've build my system heavily depending on frontmatter data and I use tags only for status.

I want to be able to distinguish if a marker is a building, a thought, a person, a historic monument (or the era of a building) via bird's eye view, without hovering over it. And if possible, filtering them based on metadata (Like, I just want to see modern buildings on a historic area). Just like how it is with tags. 

I'm not a coder so I don't know if it'll help but I kind of feel Supercharged Links Plugin can be an inspiration, maybe?

I literally signed up to GitHub for this request :) I hope I was able to use it correctly.

**Comment by Calorion** [comment]
I believe it can already do what you want. From the readme:

>Note Frontmatter

>The markerFile, markerFolder, markerTag, filterTag, linksTo, and linksFrom parameters tell the plugin where to look for notes. The notes themselves determine how the markers are created, using note frontmatter tags.

**Comment by caglarongan** [comment]
The markerFolder, markerTag, linksTo etc. searches for the notes, which is already very powerful.
But only the tags determine the style of the marker (the color and fa icon).
> The notes themselves determine how the markers are created, using note frontmatter ***tags*** 

What I'm trying to achieve is something like:
If  `Colosseum.md` has `type: building` as frontmatter, the map marker will have a `fa-building` icon.
And if `Colosseum.md` also has `material: travertine` field, the marker will have the color `(0.87, 0.82, 0.73)`
So when I look at the map, I can see the distribution of the materials/styles/eras at glance.

It doesn't have to have that advanced incremental styling. I'm more than happy to create another marker style for every combination.

**Comment by valentine195** [comment]
You can control the marker type with the `mapmarker` frontmatter tag. https://github.com/valentine195/obsidian-leaflet-plugin#mapmarker
