### ISSUE TITLE
Mobile Issue on Android and IOS

### ISSUE THREAD

**Issue by K-Gamer22** [valentine195/obsidian-leaflet-plugin#325]
I’m trying to get the Obsidian Leaflet plugin to work on my IPad/Android phone. 

The plugin says on both devices: "Failed to load obsidian-leaflet-plugin" 

Technical information:
Android: 12
IOS: 15.5
Obsidian App: 1.4.1
Plugin: 5.1.0

**Comment by Calorion** [comment]
This is an issue with 5.1.0 specifically. I just updated and it will no longer enable.

**Comment by valentine195** [comment]
Thanks, the lib used in the PR for that release must not be mobile compatible. My fault for not testing that. 

You can manually roll back by downloading the old release from the repo and replacing the main.JS file but I'll try to find a solution today.

**Comment by matthewturk** [comment]
This is my fault, and I'll work on a solution. My apologies. I can replicate it here.

**Comment by matthewturk** [comment]
I think that the issue is that the zlib module is not finding the dependencies, which might require modifying the obsidian build.  The solution I'm going to try to implement is to use [pako](https://www.npmjs.com/package/pako) which is a pure-JS library to do the same thing.

**Comment by Calorion** [comment]
Looks like you're not the only one having this problem: https://github.com/swar8080/obsidian-plugin-update-tracker/issues/5
