### ISSUE TITLE
[FEAT] Possible to run action by click on marker?

### ISSUE THREAD

**Issue by Quorafind** [valentine195/obsidian-leaflet-plugin#35]
It will be nice that allows us click on marker and then runs different actions.

Here is why I need this. I used leaflet plugin to review a knowledge:

https://user-images.githubusercontent.com/13215013/116787325-f039ae00-aad5-11eb-96f9-df6e3b1b2a70.mp4

But I need every marker works with different actions, like easy\normal\diffcult and output different text I need.

It will be more useful for me that allows me to run actions with leaflet in Obsidian.

**Comment by valentine195** [comment]
I'm not sure I understand your request. 

What are the different actions you'd like to perform? Would it be running an existing Obsidian command (aka something from the command palette), or something totally custom?

**Comment by Quorafind** [comment]
Running Obsidian command OR just like the buttons plugin did (if you know it)

**Comment by Moonbase59** [comment]
WARNING: This isn’t very stable and will break
- if the user switches Obsidian languages (which I do quite often)
  - Example (en→de): `Export to PDF` becomes `Nach PDF exportiern`
- if you happen to have a note with the same name as a command in the base of your vault
  - Example: `marker: Location,51,10,Export to PDF` will _start the command_ in `English` setting, _open the note_ in `Deutsch` setting.

I think this simplistic approach is a little too dangerous, don’t you?

**Comment by valentine195** [comment]
Yes, probably a little simplistic. As far as I am aware, though, Obsidian doesn't expose an API to execute an existing command. This is using the same method as the "buttons" plugin mentioned above (from what I can tell).

**Comment by Quorafind** [comment]
@valentine195  Quick question, how to add trigger or how to add command to it?

**Comment by valentine195** [comment]
Put the **full name** of the command in the "Marker Target" field.

Either:

```leaflet
marker: default, 1, 2, Export to PDF
```

or

![image](https://user-images.githubusercontent.com/38669521/117294974-49407380-ae41-11eb-9f7e-8db51534c23d.png)

**Comment by valentine195** [comment]
FYI as of 3.4.0 you have to turn the "Command Marker" toggle **ON** when editing a marker to execute a command.
