### ISSUE TITLE
Improvement for marker visibility

### ISSUE THREAD

**Issue by dmn-bernard** [valentine195/obsidian-leaflet-plugin#363]
Hello there!
I really love this obsidian plugin, thank you for all the effort you spend on it! ❤️ 👍 

I was a bit frustrated that my markers are not that visible depending on their colour and the image below them. So I came in with a tiny CSS snippet that improved a bit their overall visibility:

```css
.leaflet-marker-icon svg {
  filter: drop-shadow(1px 3px 3px black);
}
```

It really improved the visibility in my view. I was thinking this could be an easy addition to the plugin itself, but I was bit too lazy to do a pull request, so I'm dropping it there 🙃 

Before
<img width="192" alt="Capture d’écran 2023-04-08 à 16 29 56" src="https://user-images.githubusercontent.com/12032776/230726748-59c2b247-f301-4584-816a-1003933d2243.png">

After
<img width="185" alt="Capture d’écran 2023-04-08 à 16 29 24" src="https://user-images.githubusercontent.com/12032776/230726730-b7a6c7e0-73a7-4b46-a04b-d0880148cae4.png">

**Comment by valentine195** [comment]
This is a great improvement, thanks for the suggestion.
