### ISSUE TITLE
Feature request: Checking coordinates

### ISSUE THREAD

**Issue by Scarlov** [valentine195/obsidian-leaflet-plugin#37]
Since the markers that are not hard coded into the code block will disappear after a week I though of hard coding them but found it a bit challenging. I am using an image map where coordinates are not obvious and I can't check them easily. It would be very useful if I could just press ```alt + left mouse click``` for a notification to pop up with the coordinates of the point I am clicking on.

**Comment by valentine195** [comment]
Sorry, I think maybe the documentation isn't clear on how that works. I'll update it, but here's the rundown:

When you create a marker on a map, the data for that marker is saved into the plugin data, along with a reference to all of the files that map is being used on.

If, at some future point, the map is _no longer associated with any files_ (as in, the files have been deleted, or the map was removed from the files), it will _then_ delete marker data after 7 days.

**Comment by valentine195** [comment]
Added <kbd>Alt<kbd>-click on markers to reveal coordinates in 3.2.0

**Comment by Moonbase59** [comment]
I don’t actually use it, but `Alt+Click` didn’t work here (Obsidian 0.11.13/AppImage, Installer 0.10.11, Linux Mint 20.1/Cinnamon).

**Comment by valentine195** [comment]
Interesting. Does anything at all happen? Any errors on the console?

**Comment by Scarlov** [comment]
It works for me.
