### ISSUE TITLE
Possible issues with marker target commands

### ISSUE THREAD

**Issue by Moonbase59** [valentine195/obsidian-leaflet-plugin#38]
Re #35:

WARNING: This isn’t very stable and will break
- if the user switches Obsidian languages (which I do quite often)
  - Example (en→de): `Export to PDF` becomes `Nach PDF exportieren`
- if you happen to have a note with the same name as a command in the base of your vault
  - Example: `marker: Location,51,10,Export to PDF` will _start the command_ in `English` setting, _open the note_ in `Deutsch` setting.
- if a plugin writer or the Obsidian translators decide to translate a command differently.

I think this simplistic approach is a little too dangerous, don’t you?

_Originally posted by @Moonbase59 in https://github.com/valentine195/obsidian-leaflet-plugin/issues/35#issuecomment-832950864_

**Comment by valentine195** [comment]
Yeah, probably. This (honestly) was a quick end-of-day feature add to get the functionality built in for the user in issue #35.

Ultimately since Obsidian (I believe) does not expose the registered commands in their API, I'm not sure how safe I can really make this functionality. Probably putting a warning on it in the documentation will be enough, referencing your caveats.

**Comment by Moonbase59** [comment]
Hmm. Not to turn someone down, but I doubt the usage metaphor. With a marker on a map, upon hovering or clicking, I’d expect "more info", "zoom to it" or "go there", much like your original version offers. But _not_, probably unexpectedly, or even dangerous, _commands_ being executed, or files created.

This may be convenient for a (very) few users, but, honestly, if it were my project, I’d turn this FR down. The next user will probably come and want shell scripts executed …

Maybe when an Obsidian command can be executed via some safer mechanism, like a command ID or the like, this could be re-evaluated, or a separate "command plugin" written.

Just my 2¢.

**Comment by valentine195** [comment]
I added this specific functionality because there was already a plugin in the community list that exposed it in the same way, and also the fact that a user has to explicitly enter the name of command to make it work. _However_, I agree that there is a potential collision issue if the user has a note by the same name as some random Obsidian command, so I think I will do two things:

1. Make it clear in the docs that using this feature could have unintended consequences.
2. Have a flag that must be set on a marker to tell the plugin that this marker will be executing an Obsidian command.

2 will prevent unintentional collisions with notes.

**Comment by Moonbase59** [comment]
Yeah, if you want to keep it, a flag seems a good idea to avoid erroneous file creations and the like.

**Comment by Moonbase59** [comment]
3.4.0: Best of both worlds, hee hee. I like best the "X No command found!" when working in the "wrong" language. :-)

Hopefully someday will come a better way to access commands.

**Comment by valentine195** [comment]
Closing this issue as I think the toggle prevents accidental collisions

**Comment by Moonbase59** [comment]
Addendum: They actually _do_ have nice ids, see `app.commands` in dev console. Wonder if these could be used, since they don’t change with language (plus you get the nice translation string as a bonus!).

![obsidian-command-ids](https://user-images.githubusercontent.com/3706922/118371127-65fc4a00-b5ab-11eb-97ff-e552af857bed.png)

**Comment by valentine195** [comment]
Yeah, I saw this when initially putting this functionality in, but these ids aren't revealed to the user at all. I guess I could store the ID when first created, though, instead of the name...

**Comment by Moonbase59** [comment]
Pondering … These currently enabled commands could of course be shown using `dataviewjs`:

```javascript

let cmds = dv.array(Object.entries(app.commands.commands))
    .sort(v => v[1].id, 'asc');
dv.paragraph(cmds.length + " commands currently enabled.<br><br>");

dv.table(["Command", "Name"],
  cmds.map(v => [v[1].id, v[1].name])
  );

```

**Comment by valentine195** [comment]
> I guess I could store the ID when first created, though, instead of the name...

This change will be in the next release.

**Comment by Moonbase59** [comment]
Just for the record: I wrote a small DataviewJS script to show the current Command Palette:
https://forum.obsidian.md/t/dataviewjs-snippet-showcase/17847/13?u=moonbase59

**Comment by Moonbase59** [comment]
> > I guess I could store the ID when first created, though, instead of the name...
> 
> This change will be in the next release.

How then would we add a `commandMarker` now? Wouldn’t it get problematic when we specified it using Language A, then switch Obsidian to Language B? The map could never be re-created from the codeblock while we were staying in Language B …

**Comment by valentine195** [comment]
A commandMarker created in the map block would not update, correct. Not sure that's going to be possible to fix cleanly, since the command IDs are not exposed to the user anywhere except in the console.

**Comment by Moonbase59** [comment]
But how else could I create a command marker? "Bulk edit" shows no option for that (if so, a list could be shown and the command id used internally).

Keeping a list in your docs and using the internal id seems unreasonable, since plugins can introduce lots of new ones. Hm.

**Comment by valentine195** [comment]
Yeah, it's tricky.

A marker can be "converted" into a `commandMarker` in the marker context modal (right click on a created marker). That's the only way right now outside of the `commandMarker` parameter.

**Comment by Moonbase59** [comment]
Ah, didn’t know _that one_! Needs to get into the docs … This actually seems a good way to me—and it works!

So why not tell people to set a marker, convert it, and basta? And just "secretly" have the nerdy feature of using the ids for the code block `commandMarker` entries?

**Comment by valentine195** [comment]
https://github.com/valentine195/obsidian-leaflet-plugin/blob/master/README.md#obsidian-commands-as-links

It actually was, but accidentally under the Bulk Edit heading. I just fixed it. :grin:

**Comment by valentine195** [comment]
Also - I'm slowly creating an actual documentation website to host on github. Just need to find the time.

**Comment by Moonbase59** [comment]
Yeah, I know how that is—we all probably like better to comment code instead of always running after keeping user docs up-to-date … sigh.

**Comment by Moonbase59** [comment]
Just found that it actually puts the command id into the "file to open" field when bulk editing, hee hee.

**Comment by valentine195** [comment]
> Just found that it actually puts the command id into the "file to open" field when bulk editing, hee hee. It can’t be changed there, unfortunately. ;-)

Actually, now that you mention it, it should be able to be changed there (just no command marker <-> note marker toggle). I'm assuming it opens a note list suggestion box on click? I can detect that it's a command marker and open the command suggestion box instead.

**Comment by Moonbase59** [comment]
Yep, it tries to open a file then. Interestingly, when setting "command" to "on", it initially even shows the new command id I entered, but when saving, it vanishes. I have to go back in, enable command, and select one.

**Comment by Moonbase59** [comment]
I will probably never use a command marker, but this "make a marker and then convert it to a command" might just be the thing for the command marker guys, maybe use a custom map image that shows "functions" and then be able to click around on many commands. :-)

**Comment by valentine195** [comment]
Yep! Honestly, probably won't ever use it either, but haven't gotten any complaints yet!

**Comment by Moonbase59** [comment]
I think I should update my Dataview command list with an id column, just to be sure …
