### ISSUE TITLE
3.4.0: Alt+Click on marker (reveal location) doesn’t work

### ISSUE THREAD

**Issue by Moonbase59** [valentine195/obsidian-leaflet-plugin#39]
For some reason, `Alt`+`Click` on a marker to reveal its location did never work here. Absolute low priority though.

Obsidian/AppImage 0.11.13, Installer 0.10.11, Linux Mint 20.1/Cinnamon.

**Comment by Moonbase59** [comment]
New unknown features everyday: On Cinnamon DEs, this apparently moves around the application window (as long as you hold `Alt` and the mouse). And you’re right: It disables the `MouseEvent.altKey`. Good find!

**Comment by valentine195** [comment]
Can you confirm if 3.4.1 fixes this?

**Comment by valentine195** [comment]
Dang, ok. I'll just add <kbd>Shift</kbd>-click as an option too.

**Comment by Moonbase59** [comment]
Odd that Obsidian doesn’t use <kbd>Shift</kbd>+Click to open links in a new pane—most browsers do. Otherwise, this seems to be (quite) unused on my Linux (except for a few apps using it).

**Comment by valentine195** [comment]
3.5.0 added

- Adds ability to use <kbd>Shift</kbd> alongside <kbd>Alt</kbd> to display marker coordinates
