### ISSUE TITLE
Add option for invert color 

### ISSUE THREAD

**Issue by trungng2006** [valentine195/obsidian-leaflet-plugin#44]
Usecase: to convert figure into darkmode. This function would really help with using this plugin for academic figures.
Example:
![image](https://user-images.githubusercontent.com/71961905/117855187-d3169380-b2bc-11eb-90f7-74018bd59a93.png)
![image](https://user-images.githubusercontent.com/71961905/117855232-dc9ffb80-b2bc-11eb-9f8c-0354026b796c.png)

**Comment by valentine195** [comment]
`darkMode: true` parameter will be included in the next release

**Comment by trungng2006** [comment]
Thank you!
I do agree. I think for general image, using css for enlarge hover is more convenient.
But I think leaflet provide an option for user to annotate the picture (using marker to pop up note). IMO, this is a very nice feature to enhance learning.
Once again, thank you!
