### ISSUE TITLE
3.9.0: Obscure dark backgrounds, Bulk edit markers

### ISSUE THREAD

**Issue by Moonbase59** [valentine195/obsidian-leaflet-plugin#46]
Some feedback on my latest 3.9.0 tests:

- partial dark half-transparent "background" appears when editing a marker (right-click)
- partial dark half-transparent "background" appears when bulk-editing markers
- bulk edit button has no tooltip
- bulk edit now _only_ shows the manually created markers, not those from searches (good)
- if bulk edit list empty, shows a "+" button, allows to enter data that immediately gets lost.
- also nice: trying to show where you are (green circle) in map above bulk editor, **but**
  - trying to drag the map destroys screen content
  - hovering over "Zoom in/out" removes these buttons, but the tooltip stays and the "invisible" buttons can be clicked, resulting in horrible flicker, followed by a newly zoomed map
  - hovering over the ok/cancel buttons removes all markers & buttons from map

**EDIT:**
- After deleting markers from the "bulk edit" window, they’re still on the map.

![obsidian-leaflet-bug-bulkedit-drag-map](https://user-images.githubusercontent.com/3706922/118368204-1f562200-b5a2-11eb-80bc-d3a1608ffb49.png)
![obsidian-leaflet-bug-bulkedit-no-markers](https://user-images.githubusercontent.com/3706922/118368206-1feeb880-b5a2-11eb-857f-ad82899e829d.png)
![obsidian-leaflet-bug-odd-backgrounds-1](https://user-images.githubusercontent.com/3706922/118368208-20874f00-b5a2-11eb-942c-57e9bd866c80.png)

**Comment by valentine195** [comment]
Hmm, that's very odd. The modal is created using Obsidian's standard class. What version of Obsidian are you on?

**Comment by Moonbase59** [comment]
0.12.3 (AppImage), Installer 0.12.3 (because Electron update), Linux Mint 20.1/Cinnamon.

**Comment by Moonbase59** [comment]
> maybe I messed up the absolute positioning of the modal.

Maybe. 'Cause I’m one of the guys that want everything in portrait, using max. half a screen … So I can have an editor and a browser or whatever next to each other. And it feels more natural to me, like a page of paper. A readable line is only max. ~70em anyway ;-)

**Comment by valentine195** [comment]
Okay, I've been doing my testing on 12.3. Interesting.

**Comment by Moonbase59** [comment]
Typical (1920x1080) screen here:
![typical-screen](https://user-images.githubusercontent.com/3706922/118370043-24b56b80-b5a6-11eb-9f98-0a4d9493d227.png)

**Comment by Moonbase59** [comment]
Ok, as I accidentally posted in https://github.com/valentine195/obsidian-leaflet-plugin/issues/45#issuecomment-841684094, the modal background was my fault: No restart of Obsidian after updating.

So we can concentrate on the other bugs, probably all minor and easy to fix.

**Comment by valentine195** [comment]
I (think I) fixed these issues, but:

> also nice: trying to show where you are (green circle) in map above bulk editor, but
> - trying to drag the map destroys screen content
> - hovering over "Zoom in/out" removes these buttons, but the tooltip stays and the "invisible" buttons can be clicked, resulting in horrible flicker, followed by a newly zoomed map
> - hovering over the ok/cancel buttons removes all markers & buttons from map

I couldn't recreate this issue. Was this fixed with the restart of Obsidian?

**Comment by valentine195** [comment]
Please let me know if you're still experiencing these issues on 3.9.1

**Comment by Moonbase59** [comment]
You’re too fast for me lol! Testing with 0.3.5 and yes, these bugs are gone. Plus no need for sidescrolling when editing markers is great. :+1:
