### ISSUE TITLE
3.9.0: scale on real-world maps?

### ISSUE THREAD

**Issue by Moonbase59** [valentine195/obsidian-leaflet-plugin#47]
Could "scale" on real-world maps be used to scale measured distances, or would that break something else? It appears to do nothing on my example maps.

I was thinking of using a scale value to arrive at a (very rough but fast) _driving_ distance, calculated from the real distance. (See also: https://forum.obsidian.md/t/dataviewjs-snippet-showcase/17847/2)

**Comment by valentine195** [comment]
I actually did add a `distanceModifier` parameter that could be used for this.

**Comment by Moonbase59** [comment]
Damn! How could I forget! :rofl: And … a-hem … you called it `distanceMultiplier` actually. :grin:

**Comment by Moonbase59** [comment]
So cool that we can close this. :nerd_face:

**Comment by valentine195** [comment]
Whoops, so I did 😁
