### ISSUE TITLE
Add #obsidian-plugin topic to this repository

### ISSUE THREAD

**Issue by andyconlin** [valentine195/obsidian-leaflet-plugin#48]
Hey @valentine195, I like the look of what you're building here. I'm yet to give it a try personally, but I just barely mentioned it (and asked you a question) [on the forum](https://forum.obsidian.md/t/geotags-time-geography-plugin/11264/2?u=andyconlin).

I wanted to suggest that you [add the topic](https://docs.github.com/en/github/administering-a-repository/classifying-your-repository-with-topics) of ```obsidian-plugin``` to this repository to help others find it. I've been making use of [#obsidian-plugin](https://github.com/topics/obsidian-plugin) to see what's available, and I imagine others are, as well.

**Comment by valentine195** [comment]
Good call, thanks :)
