### ISSUE TITLE
Some odd effects in slide presentation mode

### ISSUE THREAD

**Issue by Moonbase59** [valentine195/obsidian-leaflet-plugin#65]
I have this map:

```leaflet
id: Friends
markerFolder: People/Friends & Family
markerFolder: +Inbox
height: 500px
lat: 51.133333
long: 10.416667
minZoom: 1
maxZoom: 18
defaultZoom: 5
unit: km
distanceMultiplier: 1.3
```
which works great in preview, but shows some quirks when using slide presentation mode:

![Schreiben - Obsidian v0 12 3_026](https://user-images.githubusercontent.com/3706922/119231500-87b47e80-bb21-11eb-8845-cd4f9d9096d6.png)

![Schreiben - Obsidian v0 12 3_027](https://user-images.githubusercontent.com/3706922/119231593-f8f43180-bb21-11eb-83d1-595872035eec.png)

![Schreiben - Obsidian v0 12 3_033](https://user-images.githubusercontent.com/3706922/119285296-06a0d880-bc42-11eb-9ed3-9a4062170476.png)

- map markers originally showed as oblique blocks ~~(gone, don’t know why)~~<ins>(turned up again)</ins>
- "Filter" shows the entries but a filter symbol and _two_ tooltips come up when hovering over it
- "Bulk edit markers" also shows 2 tooltips when hovering
- all _black_ tooltips are in the wrong position (dependent on window size)
- note preview (if enabled) isn’t shown when hovering over a marker

I assume these are all just minor CSS problems, since Obsidian seems to use a different CSS style for presentation views.

Would be great if that could be fixed, since Slides is a core plugin and it’s nice to be able to hack together a quick presentation within Obsidian.

**Comment by valentine195** [comment]
Thanks for letting me know - I've never used slides, so I didn't think to test it. I'll take a look at what's going on.

I wouldn't think you'd want to edit the map when viewing a slide - should I just remove the control boxes? Not sure how you'd want to use it.

**Comment by Moonbase59** [comment]
Well, it was just nice to be able to include maps in slides, actually. Since I’m a little into lecturing, just leave it as a normal map would function, so I can enter fullscreen (type "F") and show off what your plugin can do. :-) Or actually work with it :-)

**Comment by valentine195** [comment]
Hmm, it looks like a change I made in 3.11.0 broke the slides display entirely.

I rolled my plugin instance back to 3.10.0 and I think this is due to a large amount of CSS differences between note preview and slides. Not sure I'll be able to fix this, sorry :frown:

**Comment by Moonbase59** [comment]
Hm. Odd. @blacksmithgu seems to fight with similar issues—Dataview tables don’t show at all.

**Comment by valentine195** [comment]
That makes sense - in 3.11 I switched to creating a child component that adds the map element instead of directly replacing the code block element. This is also what Dataview does.

My guess is when Obsidian builds the slides, the child components are not allowed to be loaded for some reason.

**Comment by Moonbase59** [comment]
Maybe they really include the whole `marked` renderer that comes with `reveal.js` and actually let _that_ render the slide view? That might cause lots of new problems … but it would also explain the extra tooltips.

I wonder if something easy could be made that would allow `marked` to render the map/Dataview views (or any `MarkdownRenderChild`s) correctly.

Unfortunately, I’m not that deep into coding anymore, I just have gut feelings and ideas …

**Comment by valentine195** [comment]
So I poked around in the Obsidian source code today and found that it _is_ using Obsidian's own markdown post processor to generate the slides. It waits for the Promises of these post processors to finish before going to `reveal.js`, but I do not believe the `MarkdownChildRenderer` `onload` would be caught by that...

My guess: `reveal.js` stops the DOM manipulation before this can occur? I've never used the library, so not sure.

**Comment by Moonbase59** [comment]
Using 3.13.4, a map looking and working ok in preview now displays as a grey block in presentation mode. (Better than with the version before where it displayed nothing, but still worse than a few versions backwards, where it at least displayed the map and you could interact with it, even if the tooltip popups were in the wrong place.)

**Comment by valentine195** [comment]
This is due to b9eca4b0a17bc71dfd32f59a787f5f7d7e1bf33c, specifically:

> - Improved visual appearance of a loading map

**Comment by Moonbase59** [comment]
Maybe then this could be reported to the Obsidian dev team?

**Comment by valentine195** [comment]
I'm going to close this - I've been trying to do tinker with it, but I don't think it will ever work without a change in the way Obsidian's API handles PDF exporting.
