### ISSUE TITLE
3.12.1 – Markers generated from notes can be deleted

### ISSUE THREAD

**Issue by Moonbase59** [valentine195/obsidian-leaflet-plugin#68]
Just a small one: On a map with markers generated by searching notes, these can be deleted (but reappear when closing/reopening the map).

**Comment by valentine195** [comment]
In the right click modal?

**Comment by valentine195** [comment]
I believe this is fixed now. Can you confirm?

**Comment by Moonbase59** [comment]
Absolutely. Let’s close it.
