### ISSUE TITLE
Custom Image Coordinates

### ISSUE THREAD

**Issue by valentine195** [valentine195/obsidian-leaflet-plugin#74]
Can we set a geographic coordinate in the upper left corner of the empty map and a geographic coordinate in the lower right corner of the map, so as to endow the empty map with geographic coordinates? In this way, I have a large amount of geocoordinate data available to import into the plug-in.

_Originally posted by @zhubib1234 in https://github.com/valentine195/obsidian-leaflet-plugin/discussions/54#discussioncomment-792951_

**Comment by zhubib1234** [comment]
Is there a way?

**Comment by valentine195** [comment]
I have not had a chance to work on this.

**Comment by valentine195** [comment]
Please see [this](https://github.com/valentine195/obsidian-leaflet-plugin#bounds) section of the documentation for the new `bounds` parameter.
