### ISSUE TITLE
Darkmode: set Sepia to 0

### ISSUE THREAD

**Issue by trungng2006** [valentine195/obsidian-leaflet-plugin#78]
Would you please kindly edit the darkmode to set Sepia to 0 in order to help increase contrast?
(or it can also be an option within the darkmode command)

**Comment by valentine195** [comment]
This can be done using a custom CSS snippet. Please see [this new section of the ReadMe](https://github.com/valentine195/obsidian-leaflet-plugin#dark-mode), and [this](https://help.obsidian.md/How+to/Add+custom+styles) and [this](https://help.obsidian.md/Advanced+topics/Customizing+CSS) section of the Obsidian documentation.

**Comment by trungng2006** [comment]
Thank you so much!
