### ISSUE TITLE
Number coded (number counter) marker

### ISSUE THREAD

**Issue by trungng2006** [valentine195/obsidian-leaflet-plugin#79]
I think that it would be nice if the marker could be number coded/count to show routes, or to guide for reading a figure:

Ex: (for illustration only)
![image](https://user-images.githubusercontent.com/71961905/120611920-3bedc780-c487-11eb-9a42-c28c32506700.png)

**Comment by valentine195** [comment]
This can be achieved by uploading your own image to use as a custom marker. Please see [this new section of the documentation on how to do this](https://github.com/valentine195/obsidian-leaflet-plugin#using-an-image-as-a-marker-icon).

**Comment by trungng2006** [comment]
Understood!
Thank you! :D
