### ISSUE TITLE
zoomDelta only works when +/- buttons on map used, not for mouse scrollwheel

### ISSUE THREAD

**Issue by Moonbase59** [valentine195/obsidian-leaflet-plugin#87]
`zoomDelta:` works fine when using the `+` and `-` buttons on the map, but apparently isn’t applied when zooming using the mouse scrollwheel. I think this should also work with the scrollwheel, because it’s so easy zooming around the map using the wheel.

**Comment by valentine195** [comment]
Interesting. These should be the same internally. I'll investigate.

**Comment by Moonbase59** [comment]
Low priority on my end, though. Just ran across it while testing.
