### ISSUE TITLE
Changing unit in code block from "km" to "mi" doesn’t work – still "km" shown

### ISSUE THREAD

**Issue by Moonbase59** [valentine195/obsidian-leaflet-plugin#92]
When changing unit in code block from "km" to "mi", after the edit "km" are still shown. Even after closing/reopening the note with the map.

Expected: All units shown in the new unit.

**Comment by valentine195** [comment]
Is this happening only in the distance control box?

**Comment by Moonbase59** [comment]
No, also in overlay popups, for instance. They stick at the old unit. But here’s an interesting one that might help pinpoint it:

- Distance boxs shows "km" in spite of me having changed `unit: mi` in the code block.
- Make _one_ distance calculation and both the distance on the line _and_ the distance box switch to `mi`.

Seems like things only updated when next time touched.

**Comment by valentine195** [comment]
I asked because I accidentally hardcoded in "km" into the distance box 😳

**Comment by Moonbase59** [comment]
Tsk tsk :rofl:
