### ISSUE TITLE
Explore support for GeoJSON files

### ISSUE THREAD

**Issue by valentine195** [valentine195/obsidian-leaflet-plugin#93]
The only other thing people pointed me at was _areas_, like the outline of a country, county, city. Most probably _much_ too complicated for this little map thing! If ever, it would probably mean using _GeoJSON_ and _[ESRI Shapefiles](https://en.wikipedia.org/wiki/Shapefile)_. Nice feature, but overkill here, I feel. I also think that Obsidian as a whole and maps insofar possible should ideally be able to run without Internet connection as far as possible—a fact many seem to forget. This won’t work for real world maps, of course.

Just in case, I attach a JSON file describing the "Landkreis Günzburg" district in Bavaria, Germany (where I live). If such should ever be used, I think it must be generated elsewhere and only _imported_ into Obsidian Leaflet somehow.

[geo-lk-günzburg.json.zip](https://github.com/valentine195/obsidian-leaflet-plugin/files/6522422/geo-lk-gunzburg.json.zip)

__Originally posted by @Moonbase59 in https://github.com/valentine195/obsidian-leaflet-plugin/issues/30#issuecomment-845913890__

- [x] Initial support added
- [x] Add `geojsonColor` parameter
- [x] Pull tooltip from feature property name
- [x] Pull style information from GeoJSON file

**Comment by Moonbase59** [comment]
Wow! I’m awfully impressed:

![Knowledgebase - Obsidian v0 12 4_136](https://user-images.githubusercontent.com/3706922/122023021-729cd980-cdc7-11eb-934c-0cca8fa8b8cc.png)

(The example GeoJSON is actually the district I live in. And I now see it’s a little coarse, have to refine some boundaries. But it’s oh so helpful to have that for visualization!)

Feedback:
- The GeoJSON layer seems on top of the (note) overlay, so no tooltip if moving into the GeoJSON area.
- Could we please have a `geojsonColor`(like `overlayColor`)? Can’t off the top of my head remember if this is coded _into_ the GeoJSON. If so, ignore my remark.

If you want to try, here’s the map note (deriving from the `-Current Location` note):

````
## Nearby

People, locations and events within `=[[-Current Location]].nearby` around location `=[[-Current Location]].location` (`=[[-Current Location]].address`).

```leaflet
id: Nearby
markerFile: [[-Current Location]]
height: 500px
minZoom: 1
maxZoom: 18
unit: km
overlayTag: nearby
overlayColor: 'rgba(218, 165, 32, .6)'
coordinates: [[-Current Location]]
zoomTag: nearby
distanceMultiplier: 1.3
geojson:
  - [[geo-lk-günzburg-2-geojson.json]]
geojsonColor: 'rgba(218, 165, 32, .6)'
```
````

**Comment by Moonbase59** [comment]
For GeoJSON popups/tooltips, coloring and styles, I’d propose the following (priority top to bottom):

- follow the [Mapbox Simplestyle](https://github.com/mapbox/simplestyle-spec/tree/master/1.1.0) to set GeoJSON marker, stroke and fill properties. This seems to be the most widely adopted standard, although [OSM seems/seemed to use "styles"](https://gis.stackexchange.com/a/22492), but that apparently can break other parsers.
- Use "title" and possibly "description" for popup/tooltip title and description.
- Additionally, pick up "name"—most of the GeoJSON tools I’ve seen use _that_ instead of "title".
- If no styling properties are given, fall back to `geojsonColor` (codeblock).
- if `geojsonColor` isn’t given, fall back to your default blue.

**Comment by valentine195** [comment]
Thanks for the suggestions - I like them.

> I made a real crashtest, using 5 un-minified GeoJSON files (see zip), 16.6MB of GeoJSON data. Worked, albeit slow. I found that minifying them helps enormously, in both speed and size (geo-bayern.json from 13.9MB to 3.5MB and much faster display). I did not use a polygon simplifier for that, just normal JSON minify.

While I was working on this, I explored offloading the GeoJSON parser to a separate thread. Unfortunately Obsidian's Electron process does not have web workers enabled 😞

Since the plugin doesn't work on mobile, I was thinking of maybe spinning up a separate Electron process to load especially large files, then killing it. That may be a little much, though 😁 

> Stacking GeoJSON layers? If using geo-germany.json, geo-bayern.json and geo-lk-günzburg-2-geojson.json on top of each other, the "smallest" must be on top of the larger ones. But I think this could be done without programming, by requiring the user to "stack" them himself in sequence in the code block, so first Germany, then Bavaria, then district of Günzburg.

This would be very hard for me to do, I think. I'll make a note of it in the ReadMe.

**Comment by Moonbase59** [comment]
> Thanks for the suggestions - I like them.

Glad to hear. You’ll never get off that Map thingy ever again, I fear … Then again, it is now officially **the best and most useful and _usable_ mapping application ever**, and a great success with all friends and colleagues I showed it off to. One day, we should think aboutmaking an Obsidian Talk about it. Or something. This is so great it really deserves a much larger audience.

> Obsidian's Electron process does not have web workers enabled

Good to know. And sad.



> I was thinking of maybe spinning up a separate Electron process to load especially large files, then killing it.

I wouldn’t. Too much stuff to handle, and everyone knows using extremely large stuff with Electron sucks. Holds true for overcomplicated GeoJSON, too. (That’s why I included the un-minified `geo-bayern.json`.)



> This would be very hard for me to do, I think. I'll make a note of it in the ReadMe.

Yup, I think that’s definitely the best strategy here, if we can guarantee that they’re included and stacked in the code block sequence.

**Comment by Moonbase59** [comment]
Pondering … I wonder if the default line and fill properties of Obsidian Leaflet could be modified to also use a stroke width of 2px and opacity of 0.6 as defaults. Somehow the "thick lines" have always subconsciously bothered me. Don’t know what others think. Only _one_ of my testers complained about them being "too thick".

**Comment by Moonbase59** [comment]
Fantastic!

In the GeoJSON, if you have a "stroke" set, it seems to generate a "fill" in the same color but less opacity, too. Intended?

Same opacity values on an overlay and within the GeoJSON seem to make a _huge_ difference (the GeoJSON being _much_ darker). I reckon there is a default opacity already set, right? So using opacity 0.6 on an overlaycolor would now set it to 0.6*0.6=0.36?

**Comment by valentine195** [comment]
> In the GeoJSON, if you have a "stroke" set, it seems to generate a "fill" in the same color but less opacity, too. Intended?

Correct, this is Leaflet's default behavior.

> Same opacity values on an overlay and within the GeoJSON seem to make a huge difference (the GeoJSON being much darker). I reckon there is a default opacity already set, right? So using opacity 0.6 on an overlaycolor would now set it to 0.6*0.6=0.36?

Both default to 0.6 opacity now. The darker color is due to how SVG elements display when stacked.

> A blue fill (#0000ff) looks rather violet, fill-opacity is 0.36 here. Is it by chance possible that you always set a fill if the stroke was set to red (in this case), so red with less opacity plus my defined blue would ADD here?

Not sure I understand this question 😁

**Comment by Moonbase59** [comment]
lol, it _looks_ to me in the latter case that a _red_ fill (maybe from the "stroke") PLUS my intended _blue_ fill are ADDED (like two on top of each other.

**Comment by valentine195** [comment]
Ah. No, that should not be the case. The fill and stroke are separate properties on the SVG.

**Comment by Moonbase59** [comment]
But then it should be _blue_, not _violet_ … I wonder. If it had two on top of each other, that would also explain the too-high density.

**Comment by valentine195** [comment]
Yes, it would. If you open DevTools, you can use the element picker to select the SVG element and see.

**Comment by Moonbase59** [comment]
Thanks. I wonder what’s happening here. Shouldn’t the same color with the same opacity _display the same_? What am I missing?

![Workspace 1_140](https://user-images.githubusercontent.com/3706922/122090019-9e3fb400-ce07-11eb-8784-d8063dbbdec8.png)

**Comment by valentine195** [comment]
Hmm, they do for me:

![image](https://user-images.githubusercontent.com/38669521/122091028-62402b00-cdd6-11eb-9a57-f9a020c05876.png)

If you scroll through the geo-json pane, are there multiple SVG elements there? It must be getting duplicated.

**Comment by Moonbase59** [comment]
Yours look the same color (plus the overlap which also looks ok to me).

Just one <g></g> element in there, with only one path. Hm.

**Comment by valentine195** [comment]
Actually, I bet I know what's going on.

Unfortunately, Leaflet's GeoJSON module does _not_ support the full CSS color space, only hex colors.  In order to support it, I'm using the [Color](https://www.npmjs.com/package/color) npm module and converting the supplied color to hex. I wonder if something is going wrong there because of the alpha value?

**Comment by Moonbase59** [comment]
Ha! Two clever people, one thought!
I tried to use pure hex now, because I thought SVG might not work with rgba():

```
{"type":"FeatureCollection","features":[{"type":"Feature","properties":{"name":"Landkreis Günzburg","title":"Landkreis Günzburg","description":"Dies ist der Landkreis Günzburg in Bayern.","stroke":"#daa520","fill":"#daa520","fill-opacity":0.6,"BL":"Bayern","county":"LK Günzburg","GEN":"Günzburg","BEZ":"Landkreis","cases7_per":155.872374,"last_updat":"21.05.2021, 00:00 Uhr"},"geometry":{"type":"Polygon","coordinates": …
```

```
overlaycolor: '#daa520'
```

but the circle is now _blue_?

![Workspace 1_141](https://user-images.githubusercontent.com/3706922/122093285-355a3b00-ce0b-11eb-9c11-6ffcf395a473.png)

**Comment by valentine195** [comment]
It's `overlayColor`

**Comment by Moonbase59** [comment]
… so it defaulted to blue. Darn, a TYPO! :rofl: :rofl: 

I have to make a note, though, that you already use a default fill opacity of 0.2 and a stroke-opacity of 0.6.

If I modify the GeoJSON now to use the same hex color, and a fill-opacity of 0.2, it looks perfectly the same. I’m happy—thanks a bundle for helping me along!

**Comment by Moonbase59** [comment]
GeoJSON to be closed, right?

**Comment by valentine195** [comment]
Yep, I think this feature is complete.

**Comment by Moonbase59** [comment]
Just for others to follow-up: I added [How to make nice GeoJSON tooltips on the map](https://github.com/valentine195/obsidian-leaflet-plugin/discussions/108) in Discussions/Show and tell.

This is relevant if you get large GeoJSON datasets from official institutions, which might not have included a "name" or "title" feature property.
